### ISSUE TITLE
Strange scroll behaviour

### ISSUE THREAD

**Issue by dmitrykurmanov** [eigenmethod/mol#103]
Вот в этом примере https://eigenmethod.github.io/mol/app/supplies/ заметил немного странное поведение прокрутки. Если хочется мышкой утянуть прокрутку сразу в самый низ, то в какой - то момент она перепрыгивает на начало.

Прилагаю ссылку на гифку https://drive.google.com/open?id=0B-WDXlj0zYOUNF9Zbk05eGZuQms

Chrome 55.0.2883.87 m (64-bit)

PS возможно дублирует https://github.com/eigenmethod/mol/issues/70

**Comment by nin-jin** [comment]
Это особенность ленивого рендеринга. Так как мы не знаем заранее высоту всего контента в области прокрутки, то задаём ему минимальную высоту равную сумме минимальных высот вложенных блоков. По мере прокрутки, всё больше рендерится блоков и как следствие, получается более точная высота контента, из-за чего ползунок начинает отставать от курсора мыши. Если отвести мышь достаточно далеко от скроллбара (вбок или ниже скроллящейся области), то позиция ползунка сбрасывается до исходной. В случае сильного отставания, лучше "перехватить" ползунок, отпустив его и схватившись за него снова. Либо воспользоваться колёсиком мыши.

Если отказаться от ленивого рендеринга, но тогда мы потеряем быстрое открытие приложения независимо от числа выводимых блоков. Так что живём пока так. Возможно в будущем будем прятать нативный скролл и велосипедить свой. Но это довольно комплексное решение.

**Comment by dmitrykurmanov** [comment]
Кстати ту же самую проблему удаётся воспроизвести в chrome://history/
