### ISSUE TITLE
FF. Появляется лишний скрол в приложении $mol_app_bench_demo 

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#112]
**Приложение:** [$mol_app_bench_demo](https://eigenmethod.github.io/mol/#demo=mol_app_bench_demo).
**Браузер:** FireFox 50.1.0.
**Детали:**
В отличии от Chrome в FF в блоке есть скрол и отображение элементов отличается (см. картинку).
![selection_550](https://cloud.githubusercontent.com/assets/4419881/22200128/e0c6c1a4-e16e-11e6-9481-bdb17f755b07.png)

**Comment by nin-jin** [comment]
Ну, это нормально. В разных браузерах визуализация может немного отличаться. В FF минимальная высота скроллящейся области больше 0.
