### ISSUE TITLE
FF, EDGE. Маленький шаг скрола в приложениях

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#113]
**Приложение:** [ $mol_app_habhub_demo](https://eigenmethod.github.io/mol/#demo=mol_app_habhub_demo)
**Браузер:** FireFox 50.1.0., Microsoft Edge 25.10586.0.0
**Детали:**
Скролл на всех страницах работает медленно (маленький шаг скрола), а особенно это заметно на страницах с текстом.

**Comment by nin-jin** [comment]
Починили, проверь, пожалуйста.

**Comment by JulyJ** [comment]
Да, проблема исправлена.
