### ISSUE TITLE
FF. Можно ввести символы в цифровые поля

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#114]
**Приложение:** [$mol_app_inventory_controller_demo](https://eigenmethod.github.io/mol/#demo=mol_app_inventory_controller_demo)
**Браузер:** FireFox 50.1.0.
**Детали:**
В поля, в которые в Chrome браузере разрешен ввод только цифр в FF можно вводить любые символы:
![selection_552](https://cloud.githubusercontent.com/assets/4419881/22200320/ac36dcfc-e16f-11e6-9aa1-2999833eb1b5.png)

**Comment by nin-jin** [comment]
@ar2r13 нам нужно решить что будем делать со вводом нечисловых символов в числовое поле.

**Comment by nin-jin** [comment]
Особенность стандартного числового поля в FF. Думаю не стоит на эту тему заморачиваться, ведь и так должно быть понятно, что нужно вводить цифры. В дальнейшем прикрутим $mol_format к $mol_number, когда его реализуем. Он позволит форматировать ввод/вывод пользователя.
