### ISSUE TITLE
FF, IE. Не отображаются чекбоксы рядом с задачами в приложении $mol_app_todomvc_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#115]
**Приложение:** [$mol_app_todomvc_demo](https://eigenmethod.github.io/mol/#supply=75BCD15#demo=mol_app_todomvc_demo)
**Браузер:** FireFox 50.1.0, Internet Exporer 11.589.10586.0, EDGE 25.10586.672.0
**Детали:**
В отличии от Chrome в FF и IE чекбоксы (как зачекнутые, так и отчекнутые) не отображаются рядом с итемами в списке:
![selection_557](https://cloud.githubusercontent.com/assets/4419881/22200314/a4bbc532-e16f-11e6-9bcd-509a21bb5f9e.png)

**Comment by nin-jin** [comment]
Тут используется стандартный дизайн из проекта ToDoMVC: https://eigenmethod.github.io/todomvc/examples/angularjs/#/

Тем не менее я немного поправил - теперь в FF показывается нормально, а в IE по прежнему не показывается. В общем, это приложение должно работать лишь под хромом.
