### ISSUE TITLE
IE 11. Не загружаются приложения $mol_app_bench_demo, $mol_app_habhub_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#116]
**Приложение:** [$mol_app_bench_demo](http://eigenmethod.github.io/mol/#supply=2#demo=mol_app_bench_demo), [$mol_app_bench_demo ](https://eigenmethod.github.io/mol/#supply=75BCD15#demo=mol_app_bench_demo). 
**Браузер:** Internet Exporer 11.0.9600.18538.
**Операционная система:** Windows 8.1 No Service Pack
**Детали:**
Запускаю приложение, загружается весь лейаут: меню, хэдер, но само приложение не грузится. В отладчике ошибка:
![selection_566](https://cloud.githubusercontent.com/assets/4419881/22209732/9f1393e8-e198-11e6-81e2-70a31a29d844.png)

В браузере Internet Explorer 11.162.10586.0 (встроен в Windows 10) проблема не воспоизводится уже.

**Comment by nin-jin** [comment]
Скорее всего потребуется какой-то полифил.

**Comment by nin-jin** [comment]
Проблема по всей видимости в том, что IE11 на Win8 не даёт доступ к имени функции через свойство name. Поэтому имя получается их исходника функции и записывается в displayName.  Но наследование классов приводит к копированию этого имени и поэтому для потомков имя не перегенерируется, а берётся готовое из displayName, что приводит к тому, что не генерируются bem-классы для потомков. Как следствие - едет визуализация и падают тесты.

Переделал, чтобы имя получалось через внешний модуль $mol_func_name, но он требует наличия WeakMap.

**Comment by NatalyaBudnikova** [comment]
Проверено. Приложения открываются.
