### ISSUE TITLE
IE. Проблемы с размерами полей и контролов

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#117]
**Приложение:** [$mol_app_inventory_enter_demo](http://eigenmethod.github.io/mol/#supply=2#demo=mol_app_inventory_enter_demo) и другие
**Браузер:** Internet Exporer 11.589.10586.0, EDGE 25.10586.672.0
**Операционная система:** Windows 10 No Service Pack
**Детали:**
Формы ввода, текстовые поля и некоторые другие элменты изменили свои размеры в IE11:

![selection_568](https://cloud.githubusercontent.com/assets/4419881/22239096/db7363e4-e225-11e6-8de0-ed60f9d0a84b.png)
![selection_569](https://cloud.githubusercontent.com/assets/4419881/22239097/db7428ce-e225-11e6-8c39-8ec62eeac718.png)
![selection_570](https://cloud.githubusercontent.com/assets/4419881/22239098/db75cdaa-e225-11e6-8e4e-64b0ab0fa7b0.png)
![selection_571](https://cloud.githubusercontent.com/assets/4419881/22239406/753d9c8c-e227-11e6-833f-ba18c98c5f4d.png)
итд.

**Comment by nin-jin** [comment]
$mol_app_inventory и $mol_app_bench уже убраны из демонстраций. В остальных приложениях контролы сейчас вроде нормально показываются.
