### ISSUE TITLE
Safari, Android. Не загружается приложение $mol_app_bench_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#119]
**Приложение:** [$mol_app_bench_demo](http://eigenmethod.github.io/mol/#demo=mol_app_bench_demo)
**Браузер:** Safari 602.1 (iOS 10.2), Android 5, 6
**Детали:**
Поддержка javascript в safari - включена. Однако приложение $mol_app_bench_demo не грузится. Другие приложения грузятся успешно.

iOS:
![img_0684](https://cloud.githubusercontent.com/assets/4419881/22241603/21af491c-e231-11e6-84cf-fd52dc27ddfd.PNG)
Andoid:
![screenshot_20170126-172315](https://cloud.githubusercontent.com/assets/4419881/22334720/d18669a8-e3ec-11e6-828a-fddf0c0bb708.png)

**Comment by nin-jin** [comment]
Убрали это приложение из демок. В дальнейшем проапдейтим приложение, чтобы оно хорошо работало на маленьких экранах.
