### ISSUE TITLE
Chrome. Пропадает чекбокс при наведении в приложении $mol_app_todomvc_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#120]
**Приложение:** $mol_app_todomvc_demo
**Браузер:** Chrome Version 55.0.2883.87 (64-bit)
**Детали:**
При наведении на чекбокс (выполнено/невыполнено) он пропадает. Возможно это такой не совсем удачный hover, но выглядит это довольно странно.

![screenshot from 2017-01-24 13-24-36](https://cloud.githubusercontent.com/assets/4419881/22243568/eb35a180-e238-11e6-88e1-321e09d5e646.png)

**Comment by NatalyaBudnikova** [comment]
Проверено. Чекбокс не пропадает.
