### ISSUE TITLE
Safari, Android. Пропадает эффект выделения в приложении $mol_switch_demo_enabled

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#121]
**Приложение:** [$mol_switch_demo_enabled](https://eigenmethod.github.io/mol/#demo=mol_switch_demo_enabled)
**Браузер:** Safari 602.1 (iOS 10.2), Andoid Browser 6.0.1
**Детали:**

В отличии от десктопных (Chrome, FF) в мобильных браузерах эффект выделения элемента не появляется при смене фокуса на переключателе. Кнопки остаются серыми при переключении между ними:

![unspecified](https://cloud.githubusercontent.com/assets/4419881/22252067/094465e2-e25e-11e6-9772-41021e2870fc.png)

**Comment by JulyJ** [comment]
Похоже, что это не баг, а фича. Когда элемент в фокусе, то он подсчвечивается серым поверх белого. Если элементов в приложении несколько и фокус удается переключить на другой, то белая подсветка выбранного элемента остается. Закрываю баг.

**Comment by nin-jin** [comment]
Не, это не очевидное для пользователя поведение. Нужно поправить дизайн так, чтобы не было неоднозначности.

**Comment by NatalyaBudnikova** [comment]
Как было так и осталось.

**Comment by NatalyaBudnikova** [comment]
Тоже самое в приложении $mol_app_signup для поля Sex
![image 1](https://cloud.githubusercontent.com/assets/25827903/25576478/1bd9c4bc-2e68-11e7-8e4c-0fee178e8a53.png)
