### ISSUE TITLE
Android. Перестраивается список элементов в приложении $mol_suggest_demo_base при выборе элемента

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#122]
**Приложение:** [$mol_suggest_demo_base](https://eigenmethod.github.io/mol/#demo=mol_suggest_demo_base)
**Браузер:** Andoid Browser 6.0.1
**Детали:**

_Шаги воспроизвдения:_

1. Ввести в поле ввода несколько символов
2. Кликнуть по одному из значений в списке
3. Кликнуть по значению еще раз

_Текущий результат:_
При первом клике по элементу список перестраивается заново, при втором клике по значению оно таки подставляется в поле ввода.

_Ожидаемый результат:_
Как и на других платформах элемент сразу же подставляется в поле ввода после первого клика по нему.

**Comment by nin-jin** [comment]
Нужно перевести suggest на платформу select и починить эту проблему, если она на select тоже проявляется.

**Comment by nin-jin** [comment]
Отказались от $mol_suggest. Теперь вместо него используется [$mol_search](http://eigenmethod.github.io/mol/#demo=mol_search_demo#) основанный на $mol_select.

**Comment by NatalyaBudnikova** [comment]
Проверено в $mol_search.
При первом клике по элементу в списке элемент подставляется в поле ввода
