### ISSUE TITLE
Android. Проблемы с layout после поиска в приложении $mol_app_supplies_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#124]
**Приложение:** [$mol_app_supplies_demo](http://eigenmethod.github.io/mol/#demo=mol_app_supplies_demo)
**Браузер:**  Andoid Browser 6.0.1
**Детали:**
После использования поиска по баркоду в андроид приложении появлюятся проблемы в отображении элементов.
_Шаги воспроизведения_

1. Открыть приложение [$mol_app_supplies_demo](http://eigenmethod.github.io/mol/#demo=mol_app_supplies_demo)
2. Ввести в строке поиска любой баркод из существующих

_Текущее поведение_
После поиска:
![screenshot_20170125-123352](https://cloud.githubusercontent.com/assets/4419881/22285669/a39eaa36-e2fd-11e6-84ee-647909bd96df.png)
После выбора айтема вручную:
![screenshot_20170125-123615](https://cloud.githubusercontent.com/assets/4419881/22285670/a7667374-e2fd-11e6-990e-10d3ae936855.png)

**Comment by nin-jin** [comment]
Похоже на проблему с фокусом в $mol_stack. Его собираемся отрефакторить в ближайшее время.

**Comment by NatalyaBudnikova** [comment]
Проверено. После поиска открывается найденный эелемент
