### ISSUE TITLE
Chrome, FF. Функция выводится текстом на экран в приложении $mol_app_supplies_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#125]
**Приложение:** [$mol_app_supplies_demo](https://eigenmethod.github.io/mol/#demo=mol_app_supplies_demo)
**Браузер:**  Chrome Version 55.0.2883.87 (64-bit),  FireFox 50.1.0
**Детали:**

_Шаги воспроизведения:_

1. Открыть в новом окне приложение [$mol_app_supplies_demo](https://eigenmethod.github.io/mol/#demo=mol_app_supplies_demo)
2. Выбрать элемент в столбце со списком supplies

_Текущее поведение:_

- Один элемент отдельно не выбирается, выбираются все сразу.
- В заголовке блока mol_app_supplies_detail_id выводится текст функции:
![selection_572](https://cloud.githubusercontent.com/assets/4419881/22286727/33668e60-e301-11e6-9fad-7749a52ce043.png)

**Comment by nin-jin** [comment]
Починил.

**Comment by JulyJ** [comment]
Похоже исправлено.
