### ISSUE TITLE
$mol_app_inventory_demo. Двойной клик кнопкам в controller возвращает item в keeper

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#126]
**Приложение:** [$mol_app_inventory_demo](https://eigenmethod.github.io/mol/#demo=mol_app_inventory_demo)
**Браузер:**  Chrome Version 55.0.2883.87 (64-bit),  FireFox 50.1.0, ит.д.
**Детали:**

_Шаги воспроизведения:_

1. Открыть в новом окне приложение [$mol_app_supplies_demo](https://eigenmethod.github.io/mol/#demo=mol_app_supplies_demo)
2. Добавить в keeper несколько элементов и записать их в controller
3. Использовать даблклик\даблтап на любой из кнопок (pending\approved\rejected)

_Текущее поведение:_
При нажатии на любую кнопку дважды айтем переносится обратно в keeper. Мне кажется это поведение странным, ведь approved айтемы не должны возвращаться в keeper?

**Comment by nin-jin** [comment]
Дело в том, что нажатие на текущее значение сбрасывает его на дефолтное. Нужно запрещать "откликивать" переключатель статусов.

**Comment by nin-jin** [comment]
Сделано в ветке https://github.com/eigenmethod/mol/tree/new-hh-api
