### ISSUE TITLE
Дублирующиеся items в приложении $mol_app_todomvc_demо cчтаются за один item

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#127]
**Приложение:** $mol_app_todomvc_demo
**Браузер:**  Chrome Version 55.0.2883.87 (64-bit),  FireFox 50.1.0, Android v6.0.2
**Детали:**

_Шаги воспроизведения:_

1. Открыть 2 инстанса приложения в разных вкладках
2. Добавить одинаковые итемы в список todo
3. Обновить в одной из вкладок страницу, чтоб все items отобразились
3. Отметить один из них, как выполненый

_Текущее поведение:_
Второй тоже отмечается, как выполненый.
https://www.dropbox.com/s/ibu3t55dz85phkq/video.mp4.ogv?dl=0 - видео воспроизведения.

**Comment by nin-jin** [comment]
Там используется рантайм счётчик для задания идентификаторов задачам. Имеет смысл либо хранить счётчик в локальном хранилище, либо отказаться от него в пользу взятия идентификатора на 1 больше максимального идентификатора в списке. Нужно сравнить производительность обоих подходов.
