### ISSUE TITLE
Using Node.js modules in *.view.ts files

### ISSUE THREAD

**Issue by romandragan** [eigenmethod/mol#128]
How can I use installed Node modules (for example https://www.npmjs.com/package/email-validator) in my *.view.ts file?

Simply doing `$node['email-validator'].validate(this.email());` is not working and gives `Cannot find name '$node'.` error on build.

**Comment by romandragan** [comment]
Unfortunately, something like `new $node['email-validator'];` or `$node['email-validator'].validate(this.email())` not working. It still gives `Cannot find name '$node'` error.

**Comment by nin-jin** [comment]
Are you pull new revision of mol?

**Comment by romandragan** [comment]
Yes, of course. Am I doing everything right? I just type:
```
$node['email-validator'].validate(this.email());
```
directly in the custom namespace/class. So it looks like that: http://prntscr.com/e0wy6l

**Comment by nin-jin** [comment]
You must use ```namespace $.$mol``` for mol-based components.

Can you publish repository with your core for my review?

**Comment by romandragan** [comment]
Here it is - https://github.com/romandragan/mol-app-example

[This](https://github.com/romandragan/mol-app-example/blob/master/webmasters/testapp/forgot_password/forgot_password.view.ts#L5) is the file, where I'm trying to use $node variable.

**Comment by nin-jin** [comment]
Sorry, i was commit not all. Please update /node/ repository.

**Comment by romandragan** [comment]
Great, now it works like a charm. Thanks a lot!
