### ISSUE TITLE
Safari. Проблемы с отображением приложения $mol_app_inventory_demo в ландшафтном режиме

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#129]
**Приложение:** [$mol_app_inventory_demo](https://eigenmethod.github.io/mol/#supply=24CB0157#demo=mol_app_inventory_demo)
**Браузер:** Safari 602.1 (iOS 10.2)
**Разрешение:** 1920 × 1080
**Детали:**

После открытия приложения в отдельной вкладке в ландшафтном режиме (горизонтальный поврот) в приложении $mol_app_inventory_demo наблюдаются проблемы (с layout?) с отображением элементов. Все, что отображается на дисплее не скролится, хотя элементы в список добавлены:

![img_0696](https://cloud.githubusercontent.com/assets/4419881/22323262/c9253df0-e3b2-11e6-80df-cb1b2a2702e0.PNG)
![img_0695](https://cloud.githubusercontent.com/assets/4419881/22323263/cab32916-e3b2-11e6-943b-66314c196fb4.PNG)

**Comment by ar2r13** [comment]
I was not able to reproduce the bug
