### ISSUE TITLE
Safari. Задисабленные числовые поля плохо читаемы

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#131]
**Приложение:** [$mol_number_demo](https://eigenmethod.github.io/mol/#supply=24CB0157#demo=mol_number_demo)
**Браузер:** Safari 602.1 (iOS 10.2)
**Разрешение:** 1920 × 1080
**Детали:**

В Safari браузере задисабленные числовые поля плохо читаются, в остальных браузерах нормально. Слишком маленькая разница в цветах, серое на сером:
![img_0700](https://cloud.githubusercontent.com/assets/4419881/22324716/e1755558-e3bb-11e6-9750-e37a8ac22bf8.PNG)

**Comment by NatalyaBudnikova** [comment]
Стало немного получше, но хотелось мы сделать более похожим как в Chrome, например
![_014](https://cloud.githubusercontent.com/assets/25827903/25525931/f7b52e82-2c19-11e7-8ff4-dadab785f7c4.png)

**Comment by nin-jin** [comment]
Убрал приглушение цвета.

**Comment by nin-jin** [comment]
Что-то не заработало. Роман, подебаж в Сафари, пожалуйста.

**Comment by muleronko** [comment]
Эта проблема не решаема
![2017-07-19 12 20 10](https://user-images.githubusercontent.com/5873373/28360039-ef0e443c-6c7c-11e7-8d22-2e215a4dbeea.png)

**Comment by nin-jin** [comment]
Лёгкое приглушение - не страшно.
