### ISSUE TITLE
Лишние элементы в таблице в приложении $mol_app_report_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#132]
**Приложение:** [$mol_app_report_demo](http://eigenmethod.github.io/mol/#demo=mol_app_report_demo)
**Браузер:** Safari 602.1 (iOS 10.2), Andoid Browser 6.0.1, Chrome Version 55.0.2883.87 (64-bit), FireFox 50.1.0.
**Детали:**

Таблица в приложении $mol_app_report_demo отображается различно на мобильных устройствах и в браузере. При этом и там и там появляются лишние строки или столбцы в таблице:

_Мобильные Браузеры_
![img_0701](https://cloud.githubusercontent.com/assets/4419881/22329762/dd1f2f3e-e3d3-11e6-88be-d1e70281aa2d.PNG)

_Десктопные Браузеры_
![joxi_screenshot_1485429679014](https://cloud.githubusercontent.com/assets/4419881/22329779/f1bf2d90-e3d3-11e6-8e88-1035075cb8fb.png)

**Comment by nin-jin** [comment]
Упростил эту демку, добавил селекты, поправил стили.

**Comment by JulyJ** [comment]
- Chrome Version 58.0.3029.81 (64-bit) - OK
- Mozilla Firefox 53.0 (64-bit) - OK
- Safari, iOS 10.3.1 - проблема актуальна:
![img_1226](https://cloud.githubusercontent.com/assets/4419881/25523267/bedf9b5c-2c0e-11e7-8767-a14bccac88fe.PNG)
- Microsoft Edge 38.14393.1066.0 (Windows 10 mobile, Lumia 550) - Проблема со стилями там актуальна:
![wp_ss_20170428_0001](https://cloud.githubusercontent.com/assets/4419881/25521967/284b13d2-2c0a-11e7-9fed-b0ccaa75153a.png)
- Safari. iOS 9.3.5 - Происходит коллизия таблицы и заголовка(тоже касается стилей):
![image](https://cloud.githubusercontent.com/assets/4419881/25522664/76d96240-2c0c-11e7-926d-9bfb55ad9dd8.png)

**Comment by nin-jin** [comment]
Боюсь появляющийся отступ снизу мы никак не уберём (не растягивать же однострочный контрол), а вот отступа справа быть не должно. А налезание шапки по всей видимости происходит из-за недавних изменений в $mol_scroll. @muleronko глянешь?

**Comment by nin-jin** [comment]
Отступа справа не наблюдаю. Снизу при переносе текста - ожидаемое поведение.
