### ISSUE TITLE
Cordova под Android. Не срабатывает чекбокс "approved"  в приложении

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#135]
**Приложение:** [$mol_app_supplies_demo](https://eigenmethod.github.io/mol/#demo=mol_app_supplies_demo)
**Браузер:**  Приложение Cordova под Android 6.0.1.
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_app_supplies_demo
2. Найти поиском supply  в состоянии Pending по коду из списка
3. Поставить чекбокс approve

_Ожидаемое поведение_
Статус карточки с соответсвующим кодом поменялся на approved

_Текущее поведение_
Статус карточки не меняется, хотя в стандартном браузере на этом же устройстве - работает.

**Comment by nin-jin** [comment]
По ходу дела статус меняется, но у чекбокса галочка невидимая.

**Comment by nin-jin** [comment]
Дублирует https://github.com/eigenmethod/mol/issues/317
