### ISSUE TITLE
Server-Side Rendering

### ISSUE THREAD

**Issue by romandragan** [eigenmethod/mol#140]
I'm trying to implement SSR. All are working fine except two issues:
- Localization not working while rendering on server. Can you give some advise about how to fill built DOM with language constants?
- Error: `sessionStorage is not defined`. Cause `sessionStorage` is not defined in server node

**Comment by nin-jin** [comment]
I just add support of localization on server side. Use `cd my/app && node -/node.js` instead of `node my/app/-/node.js` now.

Besides, i just add mock for sessionStorage for nodejs.

**Comment by romandragan** [comment]
Localization and session storage now working well. But still have another issue while rendering:

```
TypeError: owner.state_prefix is not a function
```

It's at `mol/view/view.ts:37`

Returning just empty line instead of `(<any>owner).state_prefix()` fixes problem, but it's not best option I think?

**Comment by nin-jin** [comment]
state_key uses context and no relay on owner implementation now.

**Comment by romandragan** [comment]
@nin--jin, looks like working well now.
