### ISSUE TITLE
Добавить кнопку для выбора всех вариантов реализаций

### ISSUE THREAD

**Issue by muleronko** [eigenmethod/mol#161]
Для удобства было бы круто добавить еще один чек бокс или кнопку, для выделения всех чеков в бенче - http://mol.js.org/app/bench/#bench=http%3A%2F%2Fmol.js.org%2Fapp%2Fbench%2Felements%2F#sample=#

**Comment by nin-jin** [comment]
Для списков нам потребуется чекбокс с 3 состояниями: чекнутый, нечекнутый, частично чекнутый.

**Comment by muleronko** [comment]
Закрываем, потому что в бенче могут не догрузиться какие то бенчи
