### ISSUE TITLE
Set title on file element

### ISSUE THREAD

**Issue by ar2r13** [eigenmethod/mol#170]
http://mol.js.org/#demo=mol_app_files_demo/current=http%3A%2F%2Fajaxexplorer.com%2FUser5df12c6%2FPresentation.key

Так как title не стоит на элементе, при наведении появляется undefined

**Comment by nin-jin** [comment]
Боюсь даже если установить значение атрибуту title, то дефолтный плагин, показывающий заглушку, всё-равно изменит его на undefined при наведении.
