### ISSUE TITLE
Селекты отрабатывают со второго тапа. mol_app_report_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#191]
**Приложение:** [$mol_app_report_demo](http://mol.js.org/#demo=mol_app_report_demo/)
**Браузеры:**  (мобильные устройства)
        Safari, iOS 10.3.1, iOS 9.3.5
        Microsoft Edge 38.14393.1066.0 (Windows 10 mobile, Lumia 550)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_app_report_demo
2. Кликнуть по управляющему элементу типа Select, например "1.2 Вид Единый"
3. Кликнуть по элементу повторно

_Ожидаемое поведение_
После первого клика по элементу появляется выпадающий список.

_Текущее поведение_
Первый клик по элементу - установка фокуса
Второй клик по элементу - появление выпадающего списка

**Comment by NatalyaBudnikova** [comment]
также воспроизводится в Chrome (Android 6.0.1) 
+ в приложении $mol_pop_demo
