### ISSUE TITLE
iOS. Нет плейсхолдера Name  в приложении $mol_app_hello

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#192]
**Приложение:** [$mol_app_hello](http://mol.js.org/#demo=mol_app_hello_demorm )
**Браузеры:**  (мобильные устройства)
        Safari, iOS 10.3.1, iOS 9.3.5
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_app_hello

_Ожидаемое поведение_
В текстовом поле присутвует плейсхолдер Name аналогично, как в Chrome и др браузерах

_Текущее поведение_
Плейсхолдера нет:
![img_1228](https://cloud.githubusercontent.com/assets/4419881/25535073/907c6724-2c3e-11e7-9fdb-3ced5960f8f8.PNG)

**Comment by muleronko** [comment]
Проблема решена
