### ISSUE TITLE
Недочет верстки в приложении $mol_app_lamps

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#194]
**Приложение:** [$mol_app_lamps](http://mol.js.org/#demo=mol_app_lamps_demo)
**Браузеры:**
        Safari, iOS 10.3.1
        Microsoft Edge 38.14393.1066.0 (Windows 10 mobile, Lumia 550)
        Chrome Version 58.0.3029.81 (64-bit)
        итд
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_app_lamps
2. Выбрать лампу
_Ожидаемое поведение_
Рамка вокруг лампы имеет верный отступ и не пересекается с содержимым верхнего блока описания лампы.

_Текущее поведение_
Информация о лампе перекрывается полосой рамки при определенных разрешения экрана, например ноутбук 1344х768 или iPhone 7+:
![wp_ss_20170428_0002](https://cloud.githubusercontent.com/assets/4419881/25535609/60c0a4c6-2c40-11e7-979e-3428757b9ec1.png)
![mol_app_lamps lamps information from lamptest - mozilla firefox_677](https://cloud.githubusercontent.com/assets/4419881/25535617/6e29d9c0-2c40-11e7-9f45-d93159a5bdb6.png)

**Comment by nin-jin** [comment]
Не воспроизвожу, видимо уже починили.
