### ISSUE TITLE
iOS. Перенес слов по буквам в описании контролов $mol_bar

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#197]
**Приложение:** [$mol_bar](http://mol.js.org/#demo=mol_bar_demo)
**Браузеры:**  (мобильные устройства)
        Safari, iOS 10.3, iphone 7+
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_bar

_Ожидаемое поведение_
Слова влезают целиком, приложение скролится.

_Текущее поведение_
В словах переносы по буквам:
![img_1233](https://cloud.githubusercontent.com/assets/4419881/25537248/71b631a0-2c46-11e7-8ef6-63280b371a3a.PNG)

**Comment by JulyJ** [comment]
Исправлено, но текст в контролах не выровнен и находится на разной высоте:
![image](https://user-images.githubusercontent.com/4419881/29275812-148e6172-8115-11e7-83eb-562cab3b9c71.png)

**Comment by nin-jin** [comment]
Закрываю, так как никому баг не интересен.
