### ISSUE TITLE
iOS. Таблица поднялась на title в $mol_app_report_demo на главной странице

### ISSUE THREAD

**Issue by NatalyaBudnikova** [eigenmethod/mol#198]
**Приложение:** [$mol](http://mol.js.org/#demo=mol)
**Браузеры:**  
        Safari, iOS 9.3.5 (iPad)
**Детали:**

_Шаги воспроизведения:_
1. Запустить главную страницу $mol
2. Найти приложение $mol_app_report_demo

_Ожидаемое поведение_
Таблица не залезает на title

_Текущее поведение_

![image](https://cloud.githubusercontent.com/assets/25827903/25573940/5d5f2fc8-2e52-11e7-8895-95681b9a8e2e.png)

**Comment by nin-jin** [comment]
Не воспроизвёл. Видимо уже починено.
