### ISSUE TITLE
IE. Не отображается список директорий в приложении $mol_app_files

### ISSUE THREAD

**Issue by NatalyaBudnikova** [eigenmethod/mol#199]
**Приложение:** [$mol_app_files](http://mol.js.org/#demo=mol)
**Браузеры:**  
        Microsoft Edge 20.10240.16384.0 (Windows 10, IRBIS TW38)
**Детали:**

_Шаги воспроизведения:_
1. Запустить главную страницу $mol или приложение $mol_app_files 

_Ожидаемое поведение_
Присутствует список директорий

_Текущее поведение_

![767a1bd8fa](https://cloud.githubusercontent.com/assets/25827903/25574405/c709b278-2e56-11e7-9b2c-53e9d7885342.jpg)

**Comment by JulyJ** [comment]
По-прежнему ошибка:
![selection_961](https://user-images.githubusercontent.com/4419881/29275702-a3601d06-8114-11e7-8f84-c638c9f7ba4e.png)

**Comment by nin-jin** [comment]
IE более не поддерживаем.
