### ISSUE TITLE
Chart demo application

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#2]
[Online demo](http://nin-jin.github.io/chart/)

**Comment by nin-jin** [comment]
![image](https://cloud.githubusercontent.com/assets/442988/15288590/81e83b9c-1b74-11e6-8ea0-6db119112186.png)

**Comment by nin-jin** [comment]
![image](https://cloud.githubusercontent.com/assets/442988/15288594/91558ecc-1b74-11e6-975b-9e0ed497a3e6.png)

**Comment by nin-jin** [comment]
![image](https://cloud.githubusercontent.com/assets/442988/15288599/9c48f5da-1b74-11e6-8fb0-ad68122340fd.png)

**Comment by nin-jin** [comment]
![image](https://cloud.githubusercontent.com/assets/442988/15327398/fa9f68fe-1c59-11e6-837e-a89f2767bc42.png)

**Comment by ksusharimm** [comment]
![table](https://cloud.githubusercontent.com/assets/19321145/15327483/acede00a-1c62-11e6-9abb-bd8ed4e82d63.png)

**Comment by ksusharimm** [comment]
![table](https://cloud.githubusercontent.com/assets/19321145/15328380/ba8eb196-1c65-11e6-9254-b0b1cc4de94b.png)

**Comment by ksusharimm** [comment]
![table](https://cloud.githubusercontent.com/assets/19321145/15352198/11d2ecb8-1cf4-11e6-99fa-604dd5234d50.png)

Таблица для легенды. Всё же остановилась на варианте сокращения названия показателя до двух строк. При наведении курсора показывается остальной текст. На мобильной платформе показывается текст при тапе на строку. Такой вариант выбрала для того, чтобы легенда не растягивалась на бесконечность при большом количестве показателей, в том числе с длинными предложениями. Соответственно, чтобы пользователю было легче сканировать необходимую информацию – цифры показателей.

**Comment by ksusharimm** [comment]
![3](https://cloud.githubusercontent.com/assets/19321145/15352443/4af88164-1cf5-11e6-886b-de82ac3a4363.png)

График с заштриховкой области. Проверила при двадцати показателях, борщ не должен получиться.

**Comment by ksusharimm** [comment]
![screen shot 2016-05-18 at 12 38 56](https://cloud.githubusercontent.com/assets/19321145/15354291/ee20b26e-1cfd-11e6-9db0-7f593203616e.png)

График с пунктирной линией.

**Comment by nin-jin** [comment]
> При выделении у столбиков появляется обводка по центру, цвет 131C38, толщина 2, пунктирная, округлая, длина линий 8 px для разрешения 1366x768, промежутки между линиями длиной в 6 px. Если выделена линия, а не столбик, то же самое – пунктир с длиной в 8px и промежутками в 6 px, цвет 131C38, толщина такая же как у линии. Таким образом, в промежутках должен быть виден цвет линии. Пример скидываю. Такой цвет выбран потому, что он гораздо темнее любого из цветов графиков, и этот цвет будет использоваться как дополнительный к акцентному (он будет фоном для шапки или боковой панели). 
> Можно ли анимировать пунктирное выделение чтобы оно двигалось по кругу? Так среди множества элементов графика выделенный элемент не потеряется.
> 

![screen shot 2016-05-18 at 12 33 34](https://cloud.githubusercontent.com/assets/19321145/15354161/6011deb2-1cfd-11e6-8f92-148921281056.png)
![screen shot 2016-05-18 at 12 33 54](https://cloud.githubusercontent.com/assets/19321145/15354163/602e8b16-1cfd-11e6-830f-2bdd2b5e3f5b.png)
![screen shot 2016-05-18 at 12 34 12](https://cloud.githubusercontent.com/assets/19321145/15354164/6057b70c-1cfd-11e6-9bf1-87f89614a7b9.png)

**Comment by ksusharimm** [comment]
Цветовая схема для графиков будет строиться следующим образом:
Каждый последующий цвет выбирается на цветовом круге как контрастный по отношению к имеющимся цветам. За "нулевой" цвет берется акцентный (поставленный по умолчанию или кастомизированный пользователем), далее по порядку контрастные по указанной схеме. Эта схема работает только для цветового тона. Для того, чтобы выбранные таким образом цвета сочетались, каждый последующий цвет также варьируется по насыщенности между 40% и 50% и по яркости между 55% и 85%.

При наведении курсора на цветной кликабельный элемент графика, его яркость понижается на 20%.

**Comment by nin-jin** [comment]
Что реализовано:
* столбчатые и линейные графики
* линейные с пунктирной штриховкой
* легенда табличного вида
* подписи к осям
* адаптивная раскладка в широком диапазоне значений
* при клике случайный показатель меняет свои значения

Что не реализовано:
* легенда для разных типов штриховок
* подписи с единицами измерения
* выделение графиков

**Comment by nin-jin** [comment]
Графики приняты, можно показывать.
