### ISSUE TITLE
Фильтр Active в приложении $mol_app_todomvc работает как All

### ISSUE THREAD

**Issue by NatalyaBudnikova** [eigenmethod/mol#201]
**Приложение:** [$mol_app_todomvc](http://mol.js.org/#demo=mol_app_todomvc_demo)
**Браузеры:**  
        Chrome 58.0.3029.81 (64-bit)
        Safari, iOS 9.3.5 (iPad)
        Microsoft Edge 20.10240.16384.0 (Windows 10, IRBIS TW38)
        Chrome 57.0.2987.132, Android 6.0.1 (Samsung)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_app_todomvc
2. Добавить несколько пунктов
3. Отметить несколько пунктов как выполнено
4. Перейти в фильтр Active

_Ожидаемое поведение_
В фильтре Active только невыполненные пункты

_Текущее поведение_
В фильтре active все пункты, включая выполненные
![_004](https://cloud.githubusercontent.com/assets/25827903/25577679/b8e8ce12-2e70-11e7-817b-362a1d38cc19.png)

**Comment by alsii** [comment]
Firefox 53.0.2. (32-bit)
