### ISSUE TITLE
Android. Не фиксируется поиск при прокрутке в приложении $mol_app_supplies

### ISSUE THREAD

**Issue by NatalyaBudnikova** [eigenmethod/mol#203]
**Приложение:** [$mol_app_supplies](http://mol.js.org/#filter/gist=180442153/demo=mol_app_supplies_demo)
**Браузеры:**  
        Internet 4.0.30-40 (Android 6.0.1)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_app_supplies
2. Прокрутить вниз список Supplies

_Ожидаемое поведение_
Поле поиска по бар коду фиксируется при прокрутке

_Текущее поведение_
Поиск не фиксируется при прокрутке 
![screenshot_20170502-095915](https://cloud.githubusercontent.com/assets/25827903/25607551/b4765dcc-2f1f-11e7-870a-8956044d1950.png)

**Comment by nin-jin** [comment]
В новой реализации он находится во внешнем не скроллящемся контейнере.
