### ISSUE TITLE
IE 11. Не отображаются данные в приложении $mol_text_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#206]
**Приложение:** [$mol_text_demo](http://mol.js.org/#demo=mol_text_demo)
**Браузеры:**  
        Internet Explorer 11.0.9600.18639 (Windows 8.1)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_text_demo

_Ожидаемое поведение_
В приложении отображаются разные виды форматирования текста

_Текущее поведение_
Пустое окно:
![selection_678](https://cloud.githubusercontent.com/assets/4419881/25610909/c15dd368-2f2d-11e7-9caf-bdcc1a068d7a.png)

**Comment by nin-jin** [comment]
Не воспроизвожу, видимо починилось вместе с #216

**Comment by JulyJ** [comment]
У меня воспроизводится по прежнему воспроизводится на IE 11.0.9600.18763

**Comment by nin-jin** [comment]
ИЕ более не поддерживаем.
