### ISSUE TITLE
iOS, IE. Сетка графика перекрывает значения осей 

### ISSUE THREAD

**Issue by NatalyaBudnikova** [eigenmethod/mol#207]
**Приложение:** [$mol_plot](http://mol.js.org/#filter/gist=180442153/demo=mol_plot_demo/supply=75BCD15)
**Браузеры:**  
        Safari, iOS 10.2.1 (iPhone 5s)
        Microsoft Edge 20.10240.16384.0 (Windows 10, IRBIS TW38)
        IE 11.0.10240.17354 (Windows 10, IRBIS TW38)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_plot

_Ожидаемое поведение_
Цвет сетки посветлее и не перекрывает значения осей, например как на Android
![screenshot_20170502-115247](https://cloud.githubusercontent.com/assets/25827903/25611050/44bbf8ca-2f2e-11e7-8941-912dbeacbcba.png)

_Текущее поведение_
iOS: 
![image 3](https://cloud.githubusercontent.com/assets/25827903/25610840/791fdaec-2f2d-11e7-8973-6239d89c35ec.png)

Microsoft Edge, IE 11: 
![95d81335d8](https://cloud.githubusercontent.com/assets/25827903/25610871/919dd182-2f2d-11e7-94e7-0967aafca85d.jpg)

**Comment by nin-jin** [comment]
Цвет сетки слишком тёмный, а должен быть тусклый. Возможно стоит вообще убрать сетку, оставив лишь линейки.
