### ISSUE TITLE
IE 11. Нет возможности пользоваться скролом с помощью мыши $mol_select_demo_colors

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#209]
**Приложение:** [$mol_select_demo_colors](http://mol.js.org/#mol_select_demo_colors)
**Браузеры:**  
        Internet Explorer 11.0.9600.18639 (Windows 8.1)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_select_demo_colors
2. Открыть выпадающий список с цветами
3.  Мышью попытаться передвинуть ползунок полосы прокрутки

_Ожидаемое поведение_
- С помощью мыши можно проскролить список

_Текущее поведение_
- При клике на полосу прокрутки выпадающее окно пропадает.
![selection_679](https://cloud.githubusercontent.com/assets/4419881/25612239/9169c158-2f32-11e7-8d04-48de448d89ed.png)

**Comment by nin-jin** [comment]
Баг в IE11-: при клике на скроллбар фокус переносится на body. 
https://stackoverflow.com/questions/2023779/clicking-on-a-divs-scroll-bar-fires-the-blur-event-in-i-e
Простого решения нет. Не вижу смысла придумывать тут какие-то адские костыли для устаревшего браузера, ведь промотать список можно колёсиком и клавиатурой.

**Comment by nin-jin** [comment]
Переоткроем, если у данной задачи появится заказчик, готовый за это заплатить :-)
