### ISSUE TITLE
IE11. Не всегда появляются выпадающие списки . $mol_select_demo_colors

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#210]
**Приложение:** [$mol_select_demo_colors](http://mol.js.org/#demo=mol_select_demo_colors)
**Браузеры:**  
        Internet Explorer 11.0.9600.18639 (Windows 8.1)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_select_demo_colors
2. Открыть выпадающий список с цветами или c месяцами кликом мыши

_Ожидаемое поведение_
- Список открывается с первого клика

_Текущее поведение_
- При клике на элемент не всегда появляется выпадающий список. Первые кликов 10 элемент не появляется, если начинает появлятся, то для воспроизведения необходимо обновить страницу.
![selection_680](https://cloud.githubusercontent.com/assets/4419881/25612618/211b910e-2f34-11e7-8f85-5eff0dc07b09.png)

**Comment by nin-jin** [comment]
Всё дело в том куда именно нажимать. Если попадать по иконке, то клик не отрабатывает.
