### ISSUE TITLE
IE11. Не отображаются данные в некоторых приложениях $mol_app_habhub_demo

### ISSUE THREAD

**Issue by JulyJ** [eigenmethod/mol#216]
**Приложение:** [$mol_app_habhub_demo](http://mol.js.org/#mol_app_habhub_demo)
**Браузеры:**  
        Internet Explorer 11.0.9600.18639 (Windows 8.1)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_app_habhub_demo
2. Выбрать статью $mol_app_bench: готовим JS бенчмарки быстро и просто, $mol_atom: теория и практика реактивности итд

_Ожидаемое поведение_
- Отображается статья

_Текущее поведение_
- Статья не отображается
![selection_687](https://cloud.githubusercontent.com/assets/4419881/25618235/d5ffc12a-2f4e-11e7-8e82-77e080cde80a.png)

**Comment by JulyJ** [comment]
Если проскролить данные в статье вниз, а потом снова вверх то они перестают отображаться.
![selection_959](https://user-images.githubusercontent.com/4419881/29270561-17b90f60-8100-11e7-879a-b4feddf05f28.png)

**Comment by nin-jin** [comment]
IE более не поддерживаем
