### ISSUE TITLE
Android. Расползается боковое меню при переходе из горизонтального в вертикальное положение

### ISSUE THREAD

**Issue by NatalyaBudnikova** [eigenmethod/mol#217]
**Приложение:** [$mol_text](http://mol.js.org/#filter/gist=180442153/demo=mol_text_demo/supply=75BCD15)
**Браузеры:**  
        Chrome 57.0.2987.132, Android 6.0.1 (Samsung)
        Internet 4.0.30-40, Android 6.0.1 (Samsung)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_text в горизонтальном положении планшета
2. Закрыть приложение, что бы на экране отобразилось боковой меню
3. Перевернуть планшет в вертикальное положение

_Ожидаемое поведение_
Боковое меню не разъезжается

_Текущее поведение_
![screenshot_20170502-164720](https://cloud.githubusercontent.com/assets/25827903/25620498/4e71f24c-2f57-11e7-9ac8-23b6fb969ba9.png)

**Comment by nin-jin** [comment]
Это нормальное поведение, если по горизонтали не хватает места для отображения второй панели, то она скрывается, а первая растягивается на весь экран.
