### ISSUE TITLE
iOS. В $mol_text пропадает блок $mol_grid при скроллинге страницы

### ISSUE THREAD

**Issue by NatalyaBudnikova** [eigenmethod/mol#219]
**Приложение:** [$mol_text](http://mol.js.org/#filter/gist=180442153/demo=mol_text_demo/supply=75BCD15)
**Браузеры:**  
        Safari, iOS 9.3.5 (iPad)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_text
2. Прокрутить страницу вниз

_Ожидаемое поведение_
Content блока $mol_grid остается на месте

_Текущее поведение_
Content блока $mol_grid пропадает
![image 5](https://cloud.githubusercontent.com/assets/25827903/25622074/f6a62966-2f5b-11e7-9b05-f554b73955ea.png)

**Comment by nin-jin** [comment]
Не удалось воспроизвести.

**Comment by JulyJ** [comment]
Проверяла на iOS 10.3.3, сейчас при скроле грида он сужается до одной строчки:
![image](https://user-images.githubusercontent.com/4419881/29273360-a86e0b80-810c-11e7-9710-f62754025ace.png)

**Comment by muleronko** [comment]
Проблему получилось повторить, и похоже проблема в самом демо примере, при уменьшение страницы (меньше чем демо текст) возможности прокрутить страницу нет. А контент подстраивается, в том числе и таблица.

**Comment by nin-jin** [comment]
Закрываю так как никому этот баг не интересен :-)
