### ISSUE TITLE
Специализация компонентов

### ISSUE THREAD

**Issue by bgnx** [eigenmethod/mol#227]
В реакте есть возможность передать все пропсы одного компонента другому попутно переопределив некоторые пропсы
```
class Component extends React.Component {
 render(){
   return <AnotherComponent {...this.props} someProp="override value"/>
 }
}
```
В $mol насколько я понял вместо композиции используется наследование и мы просто переопределяем метод какого-то пропса как если бы переопределяли метод в классе расширяя другой класс
```
$my_component $my_another_component
	some_prop \override value
```
А теперь если мне нужно не просто переопределить пропс а заодно и заврапить в еще один div то в реакте я напишу
```
class Component extends React.Component {
 render(){
   return (
    <div>
       <AnotherComponent {...this.props} someProp="override value"/>
    </div>
  )
 }
}
````
А как это сделать в $mol ?

**Comment by nin-jin** [comment]
Такой вариант оборачивания сейчас не поддерживается. А какую задачу вы пытаетесь решить? Возможно есть другой вариант решения.

**Comment by bgnx** [comment]
Я пока только сравниваю расширяемость реакта и $mol. Мне нравится идея наследования как замена композиции потому что оно быстрее. В реакте из-за такой возможности передавать пропсы все начали злоупотреблять ими, появился такой паттерн как хокки (Hight Order Components)  и все начали расширять функциональность или специализировать через эти хокки, что в итоге приводит к тому что реакту  чтобы отрендерить один компонент нужно создать целую цепочку этих компонентов-врапперов. А при наследовании сколько бы уровней специализации или расширения бы не было при рендере всегда будет создан только один объект. Но к сожалению наследование не может полностью заменить композиию из-за вот таких случаев когда нужно не просто переопределить а еще и заврапить

**Comment by nin-jin** [comment]
У нас есть 4 механизма расширения компонент:
1. Наследование. Наследуемся и переопределяем поведение, вложенные компоненты и тп. Используется когда нужно сохранить API исходного компонента.
2. Композиция. Рендерим другой компонент внутри. На выходе получается по элементу на каждый компонент. Компонент владелец выступает в качестве фасада для одного или нескольких компонент внутри.
3. Призрачная композиция ([$mol_ghost](https://github.com/eigenmethod/mol/tree/master/ghost)). Обычная композиция, но обёртка не создаёт дополнительных элементов, а "рендерится" прямо во вложенный компонент.
4. [Плагины](https://github.com/eigenmethod/mol#plugin-components). Рендерятся в элемент владельца, не создавая дополнительных элементов.

**Comment by bgnx** [comment]
Пытаюсь разобраться какой аналог будет у такого реактовского компонента чтобы не просто переопределить а добавить какой-то новый контент
```
class Component extends React.Component {
 render(){
  <AnotherComponent {...this.props}>
   {this.props.children}
   <div>new content</div>
  </AnotherComponent>
 }
}
```
В $mol есть символ ^ но он видимо работает только при передаче объекта и такой вариант у меня не компилируется
```
$my_component $my_another_component
	some_prop ^
                            \new content
```

**Comment by nin-jin** [comment]
Добавил, поддержку этого дела, нужно апнуть $mol и перезапустить сервер.

Такое должно работать:
```
$my_component $my_another_component
	sub
		\before
		^
		\after
```

**Comment by nin-jin** [comment]
Добавил, поддержку этого дела. Нужно апнуть $mol и перезапустить сервер.

Такое должно теперь работать:
```
$my_component $my_another_component
	sub /
		\before
		^
		\after
```

**Comment by bgnx** [comment]
Спасибо работает. Но я тут понял что все же не получится таким образом реализовать аналог такого компонента на реакте - насколько я понял в $mol переопределение какого-то метода и добавление нового контента будет работать только когда мы вообще не передаем какое-то значение а как только мы что-то передадим то новый контент в виде метода на классе перезатрет всю цепочку перепопеределений. То есть, расширить компонент
``` 
$my_component $my_another_component
	сhildren /
		\before
		^
		\after
````
использовать в виде 
```
$my_app $mol_view
   sub / 
       <= content $my_component
                      сhildren / \some content
```
уже не получится потому что метод с выводом \some content перезатрет метод сhildren в $my_component. В тоже время в реакте такое будет работать
```
class MyComponent extends React.Component {
 render(){
  return (
     <MyAnotherComponent {...this.props}>
       before
       {this.props.children}
       after
    </MyAnotherComponent>
  )
 }
}
function App(){
  return (
     <div>
       <MyComponent>
         some content
       </MyComponent>
  </div>
  )
}
```
Есть ли способ реализовать такое в $mol ?

**Comment by nin-jin** [comment]
Это должны быть разные свойства:

```
$my_component $my_another_component
	sub_visible /
		\before
		^
		\after
```

```
$my_app $mol_view
   sub / 
       <= content $my_component
           sub / \some content
```

**Comment by bgnx** [comment]
Я имел ввиду более общий подход когда мы выводим контент не внутри $mol_view а где-то там в глубине определив слот children. В общем я тут пришел к мысли что из-за того что метод перезатерается другим методом оставить старый апи мы не можем и в таком случае нужно добавить новый слот, например
```
$my_component $my_another_component
	сhildren /
		\before
		newchildren /
		\after
```

**Comment by nin-jin** [comment]
Да, именно так, ведь семантика этих свойств получается разная. Именно поэтому во многих местах можно встретить такие обороты:

```
$mol_list $mol_view
    sub <= rows /
```
