### ISSUE TITLE
$mol_book: open left page without other pages closing

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#228]
Для реализации таких ui паттернов как:
1. Боковое меню, которое изначально скрыто.
2. Быстрый переход ко главной навигации приложения с глубоких уровней.

Открытие:
1. Гамбургером слева (включая и заголовок окна?).
2. Свайпом слева.

Меню должно наползать, сверху, не приводя к reflow всего приложения.

**Comment by nin-jin** [comment]
Сделал пока без свайпов.

**Comment by wmakeev** [comment]
- Детектить свайп (→) открытия меню (первой страницы) с левого края экрана, а не по всей области ([пример](http://mol.js.org/#demo=mol_grid_demo), где текущая реализация работает не так как ожидается при горизонтальном скроле таблицы)
- Переключение страниц с лева на право (в т.ч. свайп ←) происходит без анимации
- Если меню (первая страница) перекрывает часть следующей страницы, то желательно визуально показать наложение (например, с помощью тени и/или затенения перекрытых страниц).
- Текущее изображение "гамбургера" (в виде точек) сильно непривычное и, на мой взгляд, не помогает лучше понять принцип работы интерфейса. Полагаю, лучше убрать точки совсем или добавить привычный "гамбургер" и сделать кликабельным только его, а не весь заголовок.

**Comment by nin-jin** [comment]
Насчёт точек - у нас в ближайшее время планируется редизайн, посмотрим что с этим сделать. Остальное поправил.

**Comment by wmakeev** [comment]
Затеняющая область при открытом меню должна перехватывать клик, вызывать событие закрытия меню, при этом событие не должно протекать на низлежащие элементы страницы.
