### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#23]
Как минимум на первое время, нам нужно подыскать набор иконок в SVG формате, которые бы подошли нам по дизайну и имели подходящую лицензию.

**Comment by depooon** [comment]
[$mol_font.zip](https://github.com/eigenmethod/mol/files/441915/mol_font.zip)
Прикрепляю архив с шрифтом.

**Comment by nin-jin** [comment]
Точнее берём иконки отсюда: https://github.com/google/material-design-icons
