### ISSUE TITLE
Не выводится дважды контент слота

### ISSUE THREAD

**Issue by bgnx** [eigenmethod/mol#230]
Есть $my_test компонент с разметкой
```
$my_test $mol_view
	sub /
		\before
		<= children /
		<= children /
		\after
```
и есть другой компонент с разметкой
```
$my_component $mol_view
	sub /
		<= child1 $my_test
			children / 
				<= subChild1 $mol_view

``` 
В приложении в итоге отрендерилось - две текстовых ноды ("before" и  "after")  и только один тег <mol_view/> хотя $my_test выводит два раза слот children

**Comment by nin-jin** [comment]
Каждому экземпляру компонента сопоставляется один dom узел. А один dom узел не может быть одновременно в нескольких местах. Поэтому попытка добавить его второй раз приводит к его перемещению, а не копированию. Кроме того, рендеринг компонента может зависеть от контекста рендеринга. Например, $mol_list рендерит столько строчек, чтобы заполнить видимую в $mol_scroll где-то выше по dom-дереву область. У вас есть какой-нибудь реалистичный кейс, где потребовалось бы рендерить один и тот же компонент в разных местах?

**Comment by bgnx** [comment]
Получается тогда в $mol невозможен такого реактовского компонента? 
```
class Component {
 render(){
   return (
    <div>
     <div>{this.prop.children}</div>
   </div>
   <div>
     <div>{this.props.children}</div>
   </div>
  )
 }
}
```  
и использование  в виде 
```
<Panel>
  <div>content</div>
</Panel>
```
 продублирует контент два раза

**Comment by bgnx** [comment]
Из реалистичных кейсов может понадобится вывести контент и его превьюху где на которой будет проставленны всякие transform css стили или могут быть еще вариант когда хотим динамически указывать в пропсах сколько раз нужно вывести слот который мы передали компоненту

**Comment by nin-jin** [comment]
Для подобных целей используются мультисвойства, которые позволяют создавать множество экземпляров компонент:

```
$my_test $mol_view
	sub /
		\before
		<= content /
		\after
	count 0
	Content!index $mol_view
```

```
content() {
	const res = []
	for( let i = 0 ; i < this.count() ; i ++ ) res.push( this.Content( i ) )
	return res
}
```

```
$my_component $mol_view
	sub /
		<= child1 $my_test
			count 10
			Content!index <= subChild!index $mol_button_minor
```
