### ISSUE TITLE
Auto build / auto reload / hot reload

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#254]
Задача: минимизировать цикл "написание кода -> сборка -> проверка".

Особенности MAM:

1. В проекте может быть много приложений/библиотек. Пересобирать их все на каждый чих будет слишком долгим.
2. Минимум ручного конфигурирования. Рабочее окружение должно сразу работать как следует, а не требовать постоянных подкручиваний настроек (выбор какое приложение автоматически собирать).

Проблемы автосборки:

1. Пользователь может изменить несколько файлов и только потом проверить результат в браузере. Получается сборка несколько раз отработает впустую. А это траты батарейки, нагрев атмосферы, замедление функций среды разработки, замедление собственно сборки.
2. Когда пользователь сохранил файл и переключился в браузер, уже могла идти предыдущая сборка, то есть финальный результат он увидит не через {время сборки}, а через {время сборки}+{время завершения предыдущей сборки}. Что даёт удвоение времени ожидания в худшем случае. Отменять предыдущую сборку в общем случае не представляется возможным. Разве что каждую сборку делать в отдельном форке и если что - прибивать его и запускать новый, но тогда каждая сборка будет с нуля без использования кешей, а это долго.
3. Пользователю не понятно актуальную версию он видит или устаревшую, а актуальная придёт чуть позже.

Текущая реализация (сборка по запросу):

1. Сборка всегда инициируется пользователем когда он ожидает получить актуальную версию посредством обновления страницы. Это гарантирует, что после загрузки будет получена актуальная версия и не будет лишней нагрузки на систему в процессе редактирования.
2. Между вычислениями отслеживаются зависимости, поэтому перезапускаются лишь те вычисления, что могут дать новый результат. Результат остальных вычислений берётся из кеша. Например, при изменении css не будет пересобран js бандл.

Проблемы текущей реализации:

1. view.tree файлы транслируются во view.tree.ts лишь при обновлении страницы. А это значит, что среда разработки не видит обновлённых типов и может показывать ошибки там, где их не будет при сборке, и наоборот - не показывать те, которые появятся. От этого же будет некорректно работать автодополнение. Очевидно, необходимо транслировать  view.tree файлы сразу при их изменении.

**Comment by punkkk** [comment]
1) На счет траты батарейки - бред. На примере вебпака можно заметить, что при хорошей сборке - это незначительная трата времени. Тем более, что ты не можешь отследить когда пользователь таки решился посмотреть в браузер и начинать собирать лишь тогда... получается экономия только нажатия F5.

2) Это не проблема, так как сейчас, например, пользователь открывает такой браузер, жмякает F5, вдруг ему приспичило поменять текст с "228" на "1488", получается та же двойная пересборка+нажатие ф5.

3) На примере того же вебпака - он отправляет сигнал в броузер и в сосноли можно увидеть сообщеньку о том, что "парень, я тут пересобираюсь"

**Comment by nin-jin** [comment]
> На счет траты батарейки - бред. 

Нет, если ты не в душном офисе сидишь, а фигачишь код, попивая Тыкиллу на лазурном берегу.

> На примере вебпака можно заметить, что при хорошей сборке - это незначительная трата времени.

Бутылочное горлышко - проверка типов, а не транспиляция.

> Тем более, что ты не можешь отследить когда пользователь таки решился посмотреть

Нажатие F5 - намерение пользователя увидеть свежий результат. Если он переключился в браузер, то вовсе не факт, что он хочет видеть свежую версию. Возможно он хочет посмотреть что-то именно в старой, чтобы продолжить править код. Видеть сломанное приложение из-за недописанного кода он точно не хочет.

> вдруг ему приспичило

Это не тот кейс, о котором стоит беспокоиться.

> в сосноли можно увидеть сообщеньку

А можно и не увидеть в окружении других сообщенек. Впрочем, вебпак умеет и на странице сообщеньки выводить, но ценой заворачивания всей страницы во фрейм.

**Comment by punkkk** [comment]
Можно просто не эмитить обновление страницы, но пересобирать то можно.

**Comment by nin-jin** [comment]
Десяток приложений на каждый чих?

**Comment by nin-jin** [comment]
Сейчас горячая сборка js бандла у меня занимает 6 секунд. Большая часть этого времени - проверка типов. Без проверки типов сё собирается за пол секунды.

Однопоточная нода пока не соберёт все бандлы (js, test.js, css) не может отдать ни один из них. Таким образом при изменении скриптов обновляются 2 бандла, что даёт задержку в 12 секунд. Есть мысль тесты не просто запускать, но и запрашивать с сервера только после загрузки страницы.

**Comment by nin-jin** [comment]
Есть такая мысль: транспилировать каждый файл независимо, подсовывая ему d.ts сгенеренный для зависимостей. Возможно это позволит очень быстро пересобирать бандл на горячую, но медленнее на холодную.

**Comment by nin-jin** [comment]
Сейчас залит компромисный вариант: в случае изменения исходников автоматически пересобираются бандлы, к которым было обращение со времени старта мам сервера. При переключении с разработки одного приложения на другое, таким образом, нужно будет перезапускать сервер, чтобы не тратить время на сборку предыдущего приложения.

**Comment by zerkalica** [comment]
Сейчас tree пересобираются в ts сразу, через watch, удобно для вывода ошибок в ide
