### ISSUE TITLE
Как делать сериализацию и десериализацию, SSR?

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#257]
Не нашел у вас способа сохранять состояние объекта и восстанавливать его, что б при восстановлении атомы становились актуальными.

У себя в [lom_atom](https://github.com/zerkalica/lom_atom/blob/master/test/mem.serialize.spec.js) я пока ничего лучше не придумал, чем вынести кэш значений атомов в отдельное свойство в хосте.

```js
        class UserService {
            @serializable @mem user(user?: string): string {
                return '111'
            }
            __lom_state: Object
        }

        const x = new UserService()
        x.__lom_state = {
            user: '111'
        }
        x.user()
        x.user('222')
        x.__lom_state.user === '222'
```

В любой момент можно сделать снапшот состояния хоста и восстановить из снапшота.

На этой технике можно строить SSR и timetravel.

А как вы это предполагаете делать?

**Comment by nin-jin** [comment]
Снепшоты не восстановят зависимости, а это чревато. Я не вижу большой пользы в таймтревеле. А для SSR снепшоты зачем? На сервере можно запускать то же самое приложение, просто подменив адаптеры к данным. Или даже не подменяя - просто за данными по http как с клиента.

Я недавно переработал хранение данных - теперь собственно значения сохраняются всё же в атом, а атом сохранятеся в WeakMap привязанный к свойству. Но для удобства отладки в объект добавляется геттер, который выдаёт атом. Получилось довольно удобно и теперь реактивные свойства адекватно работают с super. https://github.com/eigenmethod/mol/blob/master/mem/mem.ts

**Comment by zerkalica** [comment]
Ссылочность да, не будет работать, нельзя все подряд сериализовать. Подменить адаптер вокруг fetch можно конечно, я так и думал сделать в начале. Однако в таймтревеле есть польза, например для оптимистичных апдейтов или при распределенной работы с данными.

Видел WeakMap, не понял только зачем там в mem_key dict объект, а не Map-а, она быстрее и ключи простых типов и функций можно не преобразовывать в строки.

Можно еще добавить методы toJSON() {} к мапе, атомам и хосту и сделать нормальную сериализацию нужных свойств.

**Comment by nin-jin** [comment]
Если речь про undo/redo, то таймтревел тут бесполезен.

Map в консоли слишком громоздко выглядит по сравнению с обычным объектом. Простых типов-то всего-ничего: числа и строки в основном. В строку они приводятся реактивно.

Сделать-то можно, но вот цель туманна.

**Comment by zerkalica** [comment]
в общем с абстракцией над fetch понятно, норм способ, можно прикрутить какой-нибудь swarm и будут распределенная работа со стейтом и транзакции и решение конфликтов.
