### ISSUE TITLE
Composition or inheritance?

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#262]
Наследование лежит в основе mol.

Однако, во всяких умных статьях ([раз](https://dou.ua/lenta/articles/composition-vs-inheritance-in-java/),
 [два](https://www.w3resource.com/java-tutorial/inheritance-composition-relationship.php)) пишут, что наследование ради переиспользования - плохая идея.

Нет ли тут нарушения принципа Лисков (L в SOLID)? Например, когда мы в tree-компоненте, переопределяя свойство, удаляем его нафиг, записывая null.

Где та грань, за которой компонент перестает соответствовать изначально вложенному в него смыслу? И таблица становится списком или что-то вроде.

Если традиционно эту грань, через инкапсуляцию и композицию, контролирует тот, кто проектирует компонент, у вас контролирует тот, кто использует. Это конечно гибко, но его квалификация часто ниже, разумно ли отдавать компонент, который может в неумелых руках превратиться в черте что? Не является ли это еще одним способом выстрелить в ногу?

Я понимаю, что mol дает средства и для композиции и можно не использовать его наследование вовсе, однако он поощряет это использование, т.к. этому много внимания уделяется в tree.

**Comment by wmakeev** [comment]
Не знаю насколько это важно для реальных кейсов, но подобный вопрос тоже приходил в голову. Ведь tree - это про наследование, там нет возможности композиции.

**Comment by zerkalica** [comment]
Композицией тоже можно: дальше одного компонента не наследоваться и вместо наследования и изменения одного метода - заново создавать компонент с новым свойством. Т.е. приоритет дать композиции. Вопрос что меньшее зло: копипаст или бОльшая вероятность отстрелить ногу, нарушая LSP.

**Comment by nin-jin** [comment]
Наследование и композиция - два перпендикулярных понятия. И принцип подстановки Лисков - хороший индикатор, чтобы их не перепутать. Если создаваемый компонент должен соответствовать контракту другого компонента - имеет смысл использовать наследование (не обязательно от него, а возможно от общего предка, который предоставит интерфейс и его реализацию по умолчанию). Все компоненты должны соответствовать интерфейсу $mol_view, который предоставляет кучу  методов, одинаково реализовывать которые в каждом компоненте - бессмысленно, но иногда переопределять - полезно. `view.tree` - это всё же про композицию компонент и их связи. Наследование там навязывается лишь в той мере, что пользователь должен решить чьему контракту компонент должен соответствовать. 

Этот вопрос было бы проще обсуждать на конкретных примерах.
