### ISSUE TITLE
Атомы в многопоточном рантайме

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#264]
Интересно ваше виденье, как оно будет работать в каком-нибудь go, если WebAssembly допилят.
Ведь сейчас идея атомов базируется как раз на предположении, что вычисления в одном потоке. Иначе не будет работать связывание атомов.

**Comment by nin-jin** [comment]
Для отслеживания нужно использовать Task Local Storage. Например: http://vibed.org/api/vibe.core.core/TaskLocal
