### ISSUE TITLE
Mol playground

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#265]
Нет ли возможности поиграться с tree и остальным online?
Хотя бы для tree, т.к. возникает вопрос, что сгенерируется, если вот тут 3 символа убрать.

**Comment by nin-jin** [comment]
Сейчас можно лишь поредактировать компоненты через онлайн-конструктор и посмотреть какой view.tree код генерируется. Например: http://mol.js.org/#demo=mol_form_demo/edit/path

**Comment by zerkalica** [comment]
Непонятная штука, как увидеть, что будет, если я поменяю ``` value?val <=> password?val ``` на какой-нибудь ``` value <=> password?val ``` в https://github.com/eigenmethod/mol/blob/master/form/demo/demo.view.tree ?

**Comment by nin-jin** [comment]
Cейчас для этого нужно поднять девелоперский сервер у себя на машине. В перспективе онлайн-песочница, конечно бы не помешала.

**Comment by nin-jin** [comment]
Реализовано: http://mol.js.org/app/tree/-/
