### ISSUE TITLE
Поведение mol_atom.set без force

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#266]
Почему без force значение пропускается через handler, а перед этим все связи атома удаляются?
А с force - запись происходит в кэш.

Не логичнее ли наоборот? Если проводить аналогию с get: тот без force - вернет  значение из кэша, а с force - выполнит handler.

Или вот такой кейс:
Отобразили атом в компоненте, компонент подписался на атом.
А потом, где-то присвоили атому новое значение без force и связи с компонентом порвутся, атом уже не будет влиять на компонент. Что бы этого не произошло надо добавлять force.

Достаточно частый кейс, может по-умолчанию его выбирать правильнее?

**Comment by nin-jin** [comment]
Есть два основных сценария:
1. затягивание значения
2. проталкивание значения

Если свойство кешируемое, то результат обоих этих действий оседает в кеше.

Всё, что делает force - это изменяет кеш. Если изменить кеш на undefined, то это равносильно его очистке, что приводит к повторному затягиванию значения.

Если атом при затягивании от чего-то зависит, то и проталкивать он должен туда, а не просто записывать в себя. А то получится, что у состояния не будет единого источника истины, что сложно отлаживать.

**Comment by zerkalica** [comment]
На практике чем это чревато?

**Comment by nin-jin** [comment]
Если атом затянул с сервера, то и проталкивать должен на сервер. Соответственно при проталкивании будут свои зависимости. Тут лучше более конкретные кейсы обсуждать.

**Comment by zerkalica** [comment]
К примеру, автокомплит

1. Отрендерили компонент, он запросил и подписался на searchResults.
2. Ввели что-то в строку поиска nameToSearch
3. Сработал fetch, который асинхронно засетил searchResults, если force нет, то связь разрушится

```js
class AutocompleteService {
    @mem nameToSearch = ''
    @mem searchResults(next?: string[] | Error, force?: boolean): string[] {
        if (next !== undefined) return next
        const name = this.nameToSearch
        setTimeout(() => {
            fetch(`/api/autocomplete?q=${name}`)
                .then((r: Response) => r.json())
                .then((data: string[]) => {
                    this.searchResults(data)
                })
                .catch((e: Error) => {
                    this.searchResults(e)
                })
        }, 500)

        throw new mem.Wait()
    }
}
```

Не сказал бы, что это очевидное поведение.

**Comment by nin-jin** [comment]
> Сработал fetch, который асинхронно засетил searchResults, если force нет, то связь разрушится

Так он не сетить должен а пушить. Это разные направления движения данных.

![](https://habrastorage.org/getpro/habr/post_images/ccc/3a1/d76/ccc3a1d76b17523e0f1988c27c34fd8c.svg)

Да в этом конкретном кейсе вам проталкивание собственно и не нужно, поэтому хочется, чтобы сет работал как пуш, то есть чтобы атом выступал не как посредник, а как хранилище. Но в общем случае направления надо различать. Например в кейсе "загрузить имя пользователя"/"сохранить имя пользователя":

- this.user_name() - асинхронно загрузили имя пользователя
- this.user_name( 'Jin' ) - асинхронно установили имя пользователя
- this.user_name() - пока имя пользователя сохраняется, как положено ждём

Даже если данные не отправляются на сервер, лучше их сразу сохранять в локальное хранилище, чтобы пользователь не потерял введённые значения из-за перезагрузки браузера и других форс-мажоров.

**Comment by zerkalica** [comment]
Я  понимаю, что есть кейсы, где надо различать. Суть в частоте использования этих кейсов. Их меньше, ради потенциальной возможности их использовать, надо пихать force в остальные кейсы по-умолчанию? Чаще всего set именно как хранилище чаще надо использовать.

> Даже если данные не отправляются на сервер, лучше их сразу сохранять в локальное хранилище, 

Это все ваши предположения из вашего опыта. А если персональная банковская информация, то наоборот, надо что б данные как можно меньше жили и ни в коем случае их персистить нельзя. А это практически все данные в приложении.

**Comment by nin-jin** [comment]
force инкапсулируется внутри асинхронного загрузчика. Зачем выносить его во внешний интерфейс?

По вашему получается будет так:

this.user_name() - асинхронно загрузили имя пользователя
this.user_name( 'Jin' , $mol_atom_force ) - асинхронно установили имя пользователя
this.user_name() - пока имя пользователя сохраняется, как положено ждём

И зачем такое усложнение?

**Comment by zerkalica** [comment]
Не понял ваш вопрос.

Все, что я предлагаю, поменять поведение с force и без force для set, для get остается прежнее:

this.user_name( 'Jin') - асинхронно установили имя пользователя
this.user_name('Jin',  , $mol_atom_force ) - выполнили проталкивание

**Comment by nin-jin** [comment]
> this.user_name( 'Jin') - установили имя пользователя в кэше

 Зачем пользователю свойства менять кеш? Кешем управляет пусть владелец свойства.

> кейс, когда надо сохранить при записи - редкий (или объясните, где он частый кейс)

Это типичный кейс для любого изменяемого значения.

Ну, банальный пример - [$mol_state_arg](https://github.com/eigenmethod/mol/blob/master/state/arg/arg.web.ts):

value(key) затягивает dict() который затягивает href() который читает document.location
value(key,next) проталкивает в dict(next) который проталкивает в href(next) который пишет в document.location.

**Comment by zerkalica** [comment]
Идея с кэшем понятна, проблема то не в нем, а в разрыве зависимостей.

Компонент A:
this.user_name() - асинхронно загрузили имя пользователя

Где-то вне контекста компонента A (его нет в stack):
this.user_name( 'Jin' ) - асинхронно установили имя пользователя

Компонент A:
Вот этого уже не произойдет, т.к. this.user_name( 'Jin' ) порвал связь с ним:
this.user_name() - пока имя пользователя сохраняется, как положено ждём

**Comment by nin-jin** [comment]
> this.user_name() - вот этого уже не произойдет, т.к. this.user_name( 'Jin' ) порвал связь с ним

Нет, с чего бы ему рвать связь с зависимыми атомами?

**Comment by zerkalica** [comment]
В примере с автокомплитом есть компонент AutocompleteView, есть строка поиска nameToSearch и есть результаты - searchResults.

1. отрендерили компонент, nameToSearch стал мастером для searchResults и AutocompleteView
2. сработал fetch внутри searchResults и если вместо записи в кэш, выполнить проталкивание, то 3. searchResults всем своим мастерам сделает dislead, т.е. для AutocompleteView и nameToSearch
4. Т.к. searchResults зашедулил актуализацию AutocompleteView, то тот перерендерится и searchMasters станет мастером для компонента, но nameToSearch уже не станет мастером для searchResults

**Comment by nin-jin** [comment]
А, ну так это если в searchResults делать fetch. В $mol же пуш делается в $mol_http.response, а searchResults просто будет зависеть от nameToSearch и $mol_http.response.

```
@ $mol_mem
rearchResults() {
    retur nthis.$.$mol_http.resource( 'names/?query=' + this.nameToSearch() ).json()
}
```

**Comment by zerkalica** [comment]
Дело не в обертке, маскирующей этот костыль, не здесь так в другом месте вылезет. У нас псевдосинхронная парадигма, так? Нет всяким стримам, промисам и т.д. Тем не менее, уши асинхронности торчат в виде совершенно не очевидного порядка 2х строчек. Тут соглашение, что при сохранении значения - будь добр, обратись к мастер-свойствам аналогично как при чтении.

С неблокирующей асинхронной загрузкой такой конвеншен прокатывал, забыл сперва вытащить значение, а потом делать с ним вычисления - будет синхронная и только. Даже поведение с форсом очевидно. А тут очень неприятный баг, который долго искать.

**Comment by nin-jin** [comment]
Я не понимаю, где вы тут видите баг. Моя основная идея в том, что $mol_mem можно добавлять и удалять прозрачно для реализации хендлерав 90% случаев. То есть он не меняет интерфейс, а лишь оптимизирует потоки данных. Вашего `if (next !== undefined) return next` в `searchResults` вообще быть не должно ибо он только на затягивание работает.

**Comment by zerkalica** [comment]
Баг был у меня, когда я сделал проталкивание в searchResults, вместо force. Суть в том, что это момент, отписывания при проталкивании, очень неочевиден. Т.е. когда можно без force присваивать, а когда категорически нельзя.

**Comment by nin-jin** [comment]
Когда мастер пишет в слейва - он форсит. Когда слейв в мастера - он сетит. Всё просто же.

**Comment by zerkalica** [comment]
Для вас может быть, но фраза непонятная. Применительно к автокомплиту что это значит, почему я не могу в фетче делать без force?

**Comment by nin-jin** [comment]
Потому, что fetch для searchResults у вас выступает мастером.

**Comment by zerkalica** [comment]
Странные какой-то критерий. Что есть мастер тогда. В атоме searchResults, в свойстве masters, нет никакого fetch.

nameToSearch тоже мастер для searchResult, и компонента. Но когда onInput в компоненте пишет в nameToSearch, он не пушит, а сетит, от перемены их ничего не меняется.

**Comment by nin-jin** [comment]
Под мастером я подразумеваю любой источник данных.  Инкапсулируйте ваш fetch в реактивной переменной (как в $mol_http) и никакие пуши в прикладном коде вам не понадобятся. Разница с oninput в направлении: oninput - проталкивает от пользователя к источнику данных. А fetch - затягивает из источника.

**Comment by zerkalica** [comment]
А какие могут быть еще кейсы, кроме fetch?
Если кто-то со стороны значение сетит, он должен это делать без force всегда?

**Comment by nin-jin** [comment]
Конечно, это свойству решать, что делать с переданным значением (записывать в кеш или проталкивать куда-то ещё).

**Comment by zerkalica** [comment]
Этот момент бы подробнее в документации отразить.
В https://github.com/eigenmethod/mol/tree/master/mem за фразой ``` Added force support
 ``` совсем непонятно в каких случаях писать в кэш. Что в случае записи - force - это приватная деталь свойства и только.

**Comment by nin-jin** [comment]
Согласен, по хорошему там надо обстоятельно расписать всю теорию.

**Comment by nin-jin** [comment]
Обнаружил косяк в этой логике. get/set различаются по наличию первого параметра.

```
.name()
.name( 'Jin' )
```

И тот и другой могут быть асинхронными. Результаты работы обоих кешируются.  В случае get кеш можно проигнорировать с помощью force.

```
.name( undefined , $mol_atom_force )
```

В случае set такой возможности нет, что не консистентно с get. Приходится сначала сбрасывать кеш, а потом уже делать set.

```
.name( undefined , $mol_atom_force )
.name( 'John' )
```

**Comment by nin-jin** [comment]
И при сбросе кеша всё время будет загрузка данных.. фигня в общем.

**Comment by zerkalica** [comment]
В чем косяк то, в том что set с force не вызывает хэндлер, а get с force вызывает?

Я ж вроде про это и говорил, что логичнее в set логику force инвертировать.

**Comment by nin-jin** [comment]
Не просто инвертировать. set должен один раз вызвать хендлер, а потом возвращать кеш, пока ему не будет передано отличающееся значение.

**Comment by nin-jin** [comment]
Это нужно, чтобы можно было делать несколько сетов подряд:

```
@ $mol_mem
saving() {
    this.name_first( 'Jin' ) // Первый асинхронный запрос
    this.name_last( 'Nin' ) // Второй асинхронный запрос
    return 'Saved'
}
```

**Comment by zerkalica** [comment]
Все-равно не понятно проблема в чем, что кэш ресетится перед вызовом хэндлера и статус атома становится obsolete?

**Comment by nin-jin** [comment]
Нужно чтобы первый запрос отработал только один раз, иначе до второго очередь не дойдёт.

**Comment by zerkalica** [comment]
Вот такой сценарий?

1. Есть 2 последовательных вызова  this.name_first( 'Jin' ) this.name_last( 'Nin' )
2. Разресолвился второй, saving перезапустился
3. Т.к. 3й еще obsolete, а значение кэша старое, то он дергается еще раз

**Comment by nin-jin** [comment]
Не правильно написал. Если с force вызываются, то форсируется постоянно..

```
@ $mol_mem
saving() {
    this.name_first( 'Jin' , $mol_atom_force ).valueOf() // бесконечно форсим запрос
    this.name_last( 'Nin' , $mol_atom_force ).valueOf()
    return 'Saved'
}
```

А такое по идее должно нормально отработать, ибо force не сохраняется и при автоматическом перезапуске его уже не будет:

```
@ $mol_mem
saving( next? : string , force : $mol_atom_force ) {
    this.name_first( 'Jin' , force ).valueOf()
    this.name_last( 'Nin' , force ).valueOf()
    return 'Saved'
}
```

То есть force всегда должен приходить извне реактивного контекста. Если же внутри хендлера воспользоваться форсированием, то асинхронные запросы становятся бесконечными. А вот синхронным пофиг - они сразу возвращают актуальное значение.

**Comment by zerkalica** [comment]
А какой кейс этого saving?
Если отобразить статус операции, то странно как-то. А кто будет выводить Saving..., кто запускает этот saving, если кнопка, то на кой ей результат saving в onClick ?

**Comment by nin-jin** [comment]
Кейс простой:

```
@ $mol_mem
saving_data( next = null ) { return next }

@ $mol_mem
saving( next? : string , force : $mol_atom_force ) {
    if( !this.saving_data() ) return null
    this.name_first( this.saving_data().first , force ).valueOf()
    this.name_last( this.saving_data().last , force ).valueOf()
    return 'Saved'
}

click( event? : Event ) {
    this.saving_data( this.changed_data() )
}
```

**Comment by zerkalica** [comment]
Я так и не понял, зачем force вы приводили в примерах, в этом же его нет.

**Comment by nin-jin** [comment]
Правда получилось, что затягивание вызывает приводит к проталкиванию. Лучше всё же так:

```
@ $mol_mem
data( next? : { first : string , last : string } ) {
    if( !next ) return { first : this.name_first() , last : this.name_last() }
    this.name_first( next.first ).valueOf()
    this.name_last( next.last ).valueOf()
    this.changed( true )
    return next
}

click( event? : Event ) {
    this.data( this.modified_data() )
}

editing_status() {
    if( this.data() !== this.changed_data() ) return 'Changed'
    return this.changed() ? 'Saved' : 'Untouched'
}
```

**Comment by nin-jin** [comment]
force нужен, чтобы повторить запрос. Ну, например, не было сети - запрос отвалился. Но вообще говоря, форс мне нравится всё меньше и меньше. Возможно стоит отказаться от него в пользу протягивания инвалидатора через отдельное свойство.

**Comment by zerkalica** [comment]
В текущей реализации, force в set запрос не повторит же, только в кэш запишет

**Comment by nin-jin** [comment]
В текущей реализации форсированное обновление просто в 2 шага приходится делать.

**Comment by zerkalica** [comment]
Что такое форсированное обновление? Это когда безусловно надо протолкнуть новое значение, даже если оно совпадает со старым, а зачем это нужно?

**Comment by nin-jin** [comment]
Я же писал - кода предыдущее обновление закончилось ошибкой.

**Comment by zerkalica** [comment]
А можно целиком сценарий, приводящий к ошибке?

Если обновление закончилось ошибкой, то форс не нужен же, т.к. в кэше Error будет, а он по определению не равен проталкиваемому значению

**Comment by nin-jin** [comment]
Возьмём этот кейс:

```
@ $mol_mem
saving( next? : string ) {
    this.name_first( 'Jin' ).valueOf()
    this.name_last( 'Nin' ).valueOf()
    return 'Saved'
}
```

По правильному он должен отработать так:
1. Первый проход - name_first делает запрос кидает $mol_atom_wait
2. Второй проход - name_first кидает HTTP Error игнорируя переданное значение, так как оно то же, что и привело к ошибке.
3. Пользователь снова жмёт "отправить". name_first игнорирует сохранённую ошибку, делает запрос и кидает $mol_atom_wait

2 и 3 случаи противоположны. Чтобы их подружить и нужен force или что-то ещё, что позволит различать их.

**Comment by zerkalica** [comment]
Можно узнать, что вы там намутили с форсом?
```js
value( next? : Value , force? : $mol_atom_force ) : Value {
			if( next !== undefined ) {
				
				if( force === $mol_atom_force_cache ) {
					return this.push( next )
				}

				let next_normal = $mol_conform( next , this._ignore )
				if( next_normal === this._ignore ) return this.get( force )

				if(!( this['value()'] instanceof Error )) {
					next_normal = $mol_conform( next , this['value()'] )
					if( next_normal === this['value()'] ) return this.get( force )
				}

				this._next = next_normal
				this._ignore = next_normal

				force = $mol_atom_force_update
			}
			
			return this.get( force )
		}
```

Зачем ```  return this.get( force ) ``` при отсечке, он же будет undefined

Зачем вообще в случе отсечки повторов, вызывается this.get( force ), почему нельзя просто ``` this['value()'] ```. Я пытался смоделировать ситуацию, где это нужно, но не смог, в тестах это не отражено они и без этого проходят. Приходит в голову, что это нужно для ассоциации slave-master, которая есть только в get, в случаях если мы сразу set делаем, без предварительного get.

Зачем ``` force = $mol_atom_force_update ```, вроде нигде не используется.

Почему логика поменялась, если раньше был obsolete + get приводил к pull / push, то сейчас obsolete вообще выкинут и сделан get с форсом в конце, хотя вроде тоже самое получается, только в профиль.

Еще предложение - перепишите actualize без force, сделайте так, что б force дальше get/value не протекал, вызывайте прям pull+push, там где нужно, мозг сломаешь сейчас, анализируя логику атомов.

**Comment by nin-jin** [comment]
Да, я хочу уменьшить зашумлённость стека. Так как теперь get и set работают по единой логике, то имеет смысл всю её перенести в value, а get и set оставить как алиасы для совместимости. get при отсечке вызывается, чтобы протрекались зависимости и бросилось исключение если нужно. obsolete раньше вызывался чтобы форсировать вызов хендлера, что было костылём. Теперь вместо него есть force.

Однако насчёт force всё же есть ещё косяки. Например А зависит от асинхронных Б и В. А вызывается с силой и передаёт силу в Б и в В. Когда они синхронные - нет проблем. Когда же А перезапускается после асинхронного Б, то флаг силы уже не установлен и В соответственно не будет форсирован. Если же сохранять силу при перезапуске, то Б будет бесконечно перезапускаться, а до В очередь вообще не дойдёт. Возможно тут как-то сможет помочь флаг "дошло ли вышестоящее вычисление до конца".

**Comment by zerkalica** [comment]
А можете привести тест по последнему кейсу?

**Comment by nin-jin** [comment]
Так и не запилил пример. В общем, как-нибудь займусь полным рефакторингом атомов - там и примеров накидаю.
