### ISSUE TITLE
Unknown http error в mol_app_files_demo

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#268]
http://mol.js.org/app/demo/#demo=mol_app_files_demo

Падает запрос http://ajaxexplorer.com/User5df12c6/, видимо закрыли через CORS.

**Comment by nin-jin** [comment]
У меня открывается нормально. У вас какой браузер?

**Comment by zerkalica** [comment]
Ложная тревога. У меня ublock просто блокировал загрузку с него.
