### ISSUE TITLE
mol_fiber

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#270]
Интересно, как бы это выглядело для атомов.

С возможностью приоритезации.
С автоматической настройкой приоритезации под разные задачи, научить шедулер различать анимацию и пользовательский ввод.

**Comment by nin-jin** [comment]
А давно пробую разные планировщике. Остановился в итоге на текущем, когда обновление происходит в том же порядке, что и последнее исполнение. Это даёт:

1. Более-менее вменяемые стектрейсы, по которым можно понять кто кого вызвал (даже если actualize перескакивает через pull - по стектрейсу можно подняться и узнать атом, хост-объект, свойство и тп инфу).
2. Не исполнение того, что не понадобится (например, незачем обновлять блок, если мы его всё-равно удаляем).
3. В целом предсказуемый и стабильный порядок вычислений.

Использование микротасков сделает стектрейс коротким, но бесполезным. Анимации лучше делать через css. Тут главное не занимать основной поток дольше 16 мс.

Сейчас снова играюсь с квантификацией $mol_atom - в некоторых случаях улучшается отзывчивость (например, когда листаешь огромный ленивый список - скролл бегает быстро, а рендеринг добегает с задержкой), в некоторых случаях падает скорость (отрендерить за раз быстрее, чем рендерить в 10 заходов с reflow, repaint, recomposition в каждом).

**Comment by zerkalica** [comment]
Со стек трейсом в реакте как-то решили через componentDidCatch, там правда ненативный трейс.
Просто, что если расширить атомы на канвас, например игры, с множеством динамичных объектов, нагрузка может на порядки возрасти.

А чем квантификация отличается от асинхронного рендеринга в реакте? В однопоточной же среде все квантификация.

**Comment by nin-jin** [comment]
Ненативный трейс не поотлаживаешь, к сожалению. 
У меня сейчас в разработке как-раз игра со множеством объектов, правда на SVG - вроде нормально с производительностью. Но у меня ставка на ленивость - отрезаем всё невидимое, что слишком близко схлопываем вместе и тп.
Да принципиально ничем. Только тем, что квантуется не только рендеринг, но и вообще все вычисления. Хотя тут надо ещё поисследовать - некоторые вычисления может быть слишком дорого перезапускать.
