### ISSUE TITLE
Проблемы с $mol_http 

### ISSUE THREAD

**Issue by Rurik19** [eigenmethod/mol#273]
Добрый день!

Пытаюсь использовать $mol в своём проекте. Обращаюсь к стороннему API.

1)  $mol_http.json() объявлена как 
`json< Content >( next? : Content , force? : $mol_atom_force ) : Content`, 
что означает что возвращаемые данные того-же типа, что и передаваемые, а это в моём ( да и в общем) случае не так. Приходится использовать text()

2) Главная беда - с методом 'POST' $mol_http не работает!
исключение в строке 74
`throw new $mol_atom_wait( `${ method } ${ uri }` )`
не перехватывается, приложение выпадает с ошибкой
![image](https://user-images.githubusercontent.com/1955806/31384146-19a489e0-add7-11e7-90f5-0527027de5f7.png)
хотя запрос выполняется. Пробовал также класс Rest из статьи про $mol_atom, с тем-же результатом

**Comment by nin-jin** [comment]
1. По умолчанию он считает, что json передаётся и возвращается в одном формате. Если это не так, то в любом случае придётся где-то указывать типы для возвращаемого значения. Проще всего это сделать так:

```
.json( nextValue ) as any as SomeType
```

2. По умолчанию используется метод PUT, но его можно поменять:

```
resource.method_put = ()=> 'POST'
```

3. Проверьте, возможно этот запрос пройдёт и с методом GET. Гитхаб, например, позволяет получать токен так:

```
GET https://github.com/login/oauth/access_token?code={code}&client_id={id}&client_secret={secret}
```

GET запрос не потребует лишнего OPTIONS запроса для проверки разрешения делать POST запрос.

**Comment by Rurik19** [comment]
1. попробуем
2. именно так и переопределяю
3. GET не сработает в данном случае
Проблема то не в запросе. и OPTIONS и POST **выполняются нормально** и возвращают верные значения, но из-за необработанного исключения последующий код не получает результат

**Comment by nin-jin** [comment]
Видимо вы запускаете запрос в нереактивном контексте. Вам нужно использовать либо декоратор $mol_mem, либо использовать напрямую $mol_atom.

```
@ $mol_mem
token() {
    const resource = $mol_http.resource( '...' )
    resource.method_put = ()=> 'post'
    resource.headers = ()=> { ... }
    const json = resource.json( this.json() )
    ...
    return json
}
```

```
const token = new $mol_atom( 'token' , ()=> {
    const resource = $mol_http.resource( '...' )
    resource.method_put = ()=> 'post'
    resource.headers = ()=> { ... }
    const json = resource.json( this.json() )
    ...
    return json
} )
```

**Comment by Rurik19** [comment]
@mol_mem использовался. код такой
```	
@ $mol_mem
tokens_request(content: any) {
	let res = $mol_http.resource(`${this.uri()}/oauth/v2/token`)
	res.headers = () => ({
		'content-type': 'application/json'
	})
	res.method_put = () => 'POST'
	const text = res.text(JSON.stringify(content, null, '\t'))
	return JSON.parse(text)
}
```

попробую с $mol_atom

**Comment by nin-jin** [comment]
Так а потом tokens_request как используете? Его тоже в реактивном контексте надо использовать.

**Comment by Rurik19** [comment]
Использование 
```
		get_tokens() {
			const content = {
				grant_type: "password",
				client_id: this.client_id(),
				client_secret: this.client_secret(),
				password: this.credentials().password,
				username: this.credentials().login
			}
			const response = this.tokens_request(content) as { refresh_token: string; access_token: string }
			$mol_state_local.value('wallabag_refresh_token', response.refresh_token)
			$mol_state_local.value('wallabag_app_token', response.access_token)
		}
```
которая вызывается на сабмите формы
```
		event_submit() {
			this.api().uri(this.host())
			this.api().credentials({
				login: this.login(),
				password: this.password(),
			})
			this.api().get_tokens()
		}
```

**Comment by Rurik19** [comment]
поставив @ $mol_mem для api().get_tokens() получаю зацикливание 
![image](https://user-images.githubusercontent.com/1955806/31424765-812d3276-ae75-11e7-864b-11c94fea08d4.png)

**Comment by Rurik19** [comment]
колстек на запросе
![image](https://user-images.githubusercontent.com/1955806/31424861-1377a10c-ae76-11e7-832c-5b1c2a86f11a.png)

**Comment by nin-jin** [comment]
`@ $mol_mem` нужно поставить и на get_tokens, чтобы его исполнение перезапустилось после прихода ответа.

`content` у вас сейчас каждый раз генерируется новый, что приводит к новому запросу каждый раз. Поэтому формирование `content` стоит вынести в отдельное свойство и тоже закешировать его через $mol_mem.

**Comment by Rurik19** [comment]
сделал так = тоже зацикливание
```
		@ $mol_mem
		tokens_request_content() {
			return {
				grant_type: "password",
				client_id: this.client_id(),
				client_secret: this.client_secret(),
				password: this.credentials().password,
				username: this.credentials().login
			}
		}

		@ $mol_mem
		get_tokens() {
			const response = this.tokens_request(this.tokens_request_content()) 
			$mol_state_local.value('wallabag_refresh_token', response.refresh_token)
			$mol_state_local.value('wallabag_app_token', response.access_token)
		}

		@ $mol_mem
		tokens_request(content: any) {
			let res = $mol_http.resource(`${this.uri()}/oauth/v2/token`)
			res.headers = () => ({ 'content-type': 'application/json' })
			res.method_put = () => 'POST'
			return res.json(content) as any
		}
```

**Comment by nin-jin** [comment]
А `credentials` как реализован?

**Comment by Rurik19** [comment]
```
		@$mol_mem
		credentials(next?: { login: string, password: string }) {
			const creds = $mol_state_session.value('credentials', next) || { login: '', password: '' }
			return creds
		}
```

**Comment by nin-jin** [comment]
Кажется понял в чём дело, попробуйте обновить mol.

**Comment by Rurik19** [comment]
Ура! заработало!
