### ISSUE TITLE
Actions для логирования изменений стейта

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#276]
Для отладки полезно знать не только что изменилось, но и кто изменил. В mobx есть actions для этого, а в mol как решается такая же задача?

**Comment by nin-jin** [comment]
Кто изменил - это что имеется ввиду? Какое действие пользователя на каком виджете привело к изменению какого-либо стейта?

**Comment by zerkalica** [comment]
Да, что б можно было однозначно найти место в коде, где состояние поменялось, идентификация для onClick-ов и пр.

**Comment by nin-jin** [comment]
Тут нужны зоны, чтобы правильно помечать логи, даже если исполнение продолжилось асинхронно.

**Comment by zerkalica** [comment]
В mobx для этого есть [asyncAction и runInAction](https://mobx.js.org/best/actions.html).

**Comment by nin-jin** [comment]
Ну, фактически зоны с ручным приводом :-)

**Comment by zerkalica** [comment]
Можно и не с ручным, в http-обертке.

**Comment by nin-jin** [comment]
Я вот думаю заюзать console.groupCollapsed, чтобы хоть как-то упорядочить логи. Все изменения тами образом будут сгруппированы по ивентам.

**Comment by zerkalica** [comment]
А если что-то вроде redux devtools?

**Comment by nin-jin** [comment]
А чем просто консоль не угодила? Ну кроме таймтревела.

**Comment by zerkalica** [comment]
Это ж просто лог, навигация не такая удобная, нет некоторых свистелок, вроде composition tree,  как тут https://github.com/inversify/inversify-devtools

**Comment by nin-jin** [comment]
Что именно не удобно в навигации?

Не очень понял, что делает composition tree, но боюсь в более-менее крупном приложении от него будет мало пользы.

**Comment by zerkalica** [comment]
лог примитивен, поиска нет, группировки по разным критериям и т.д. В devtools то можно много накрутить, например анализ того, что чаще меняется.

**Comment by nin-jin** [comment]
Есть фильтр.
По каким критериям хотелось бы группировки?
Нужны конкретные кейсы. Для чего может быть полезна информация о том, что чаще меняется?

**Comment by nin-jin** [comment]
Я, кстати, пробовал визуализировать дерево зависимостей - получилась ерунда :-) http://nin-jin.github.io/mol/#screen=mol_tabler_demo

**Comment by zerkalica** [comment]
Тут подумать надо. Задача - сделать стейт осязаемым, чисто психологически это многим удобно, даже если практически это не особо полезно, как в redux.

Профайлер намутить можно. Навигатор по стейту.

**Comment by nin-jin** [comment]
Думаю эту задачу можно считать решённой:
![image](https://user-images.githubusercontent.com/442988/51070236-26c23500-164f-11e9-9c6b-280a044d38f2.png)

Что касается развесистого приложения для отладки, я пока не готов за такое взяться. Основная концепция $mol - по максимуму задействовать нативные средства отладки.
