### ISSUE TITLE
$mol_atom: object comparing

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#277]
Сейчас атомы сравнивают новое и старое значение на строгое равенство, плюс, если это массивы, то строго сравнивают их содержимое. Последнее позволяет безбоязненно использовать map, filter, reduce и другие весёлые методы для генерации нового значения, не беспокоясь о том, что новый массив будет иметь то же содержимое, что и старый, но будет воспринят как новое значение.

Иногда необходимо генерировать и json-объекты, которые точно так же могут иметь идентичное содержимое.

Имеет смысл детектировать json-объекты (`Object.getPrototypeOf(obj)===Object.prototype`) и сравнивать их тоже по содержимому. Примерно так:

1. Берём список ключей
2. Сравниваем длины списков
3. Пробегаемся по ключам, сравнивая значения по соответствующим ключам

Эта логика должна работать как для json-объектов, так и для массивов.

Стоит подумать и о глубоком сравнении json-объектов/массивов.

Также стоит предоставить возможность объектам самим предоставлять функцию сравнения. Полезно для объектов типа $mol_time_moment.

**Comment by zerkalica** [comment]
shallowEqual то чем не катит?
А так ли надо делать глубокое сравнение, может лучше как в mobx - умные обертки над чистыми объектами и массивами?

**Comment by nin-jin** [comment]
Тем, что объект может генериться не плоским.

А что за умные обёртки?

**Comment by zerkalica** [comment]
observable-обертки 

```js
class A {
  @observable obj ={a: '1'}
}

const a = new A()
a.obj.a = 123 // observable
```

По мне, вообще если что-то надо сравнивать, значит атомы надо дорабатывать, а изобретать очередной shoudComponentUpdate.

**Comment by nin-jin** [comment]
Может не быть никакого observable:

```
@ $mol_mem
post() {
    $mol_http.resource( ... ).json({ body : 'lol' , reactions : { 'like' : true , 'hooray' : false } }).valueOf()
}
```

Если не предпринять специальных действий, то этот код будет бесконечно слать на сервер запросы.

Так писать было бы не удобно и странно:
```
@ $mol_mem
post() {
    const json = $mol_http.resource( ... ).json
    json.body = 'lol'
    json.reactions.like = true
    json.reactions.hooray = false
    json.valueOf()
}
```

**Comment by zerkalica** [comment]
По  мне меньшее зло работать в иммутабельном стиле с такими объектами. Можно сделать хелпер, что-то вроде.

```js
   const newObj = update(obj, {request: blaBla})
```

deepEqual плохая идея, как и shouldUpdate в коде приложения.

**Comment by nin-jin** [comment]
Исходного объекта может и не быть, как в примере выше. Вообще моя идея в том и заключается, чтобы update засунуть в сам атом.

```
const a = { foo : {} , bar : {} }
state.set( a )
state.set({ foo : {} })
state.get().foo === a.foo
state.get().bar === undefined
```

**Comment by zerkalica** [comment]
В большинстве случаев shallowEqual в атоме хватит.

deepEqual борется со следствием. Смысл в оптимизации записи в объект.

Например, тут уже поздно что-то делать:

```js
const json = { body : 'lol' , reactions : { 'like' : true , 'hooray' : false } }
```

Для merge, правда deepEqual не нужен:

```js
const a = { foo : {} , bar : {} }
state.set( a )
state.set({ foo : {} })
```

Но тут ломается уже простота и прозрачность интерфейсов, хотя можно извратиться:

```js
class User {
  name: string = 'test'
  id: string = '1'
}
class A {
  @mem get user(): User { return new User() }
  @mem set user(next: $Shape<User>) {}
}
const a = new A()
a.user = {name: 'test2'}
```

**Comment by nin-jin** [comment]
> Например, тут уже поздно что-то делать

Иногда данные приходят уже куском json-а и что-то делать всё же нужно, чтобы не перевычислять все зависимости при фактическом отличие в одном поле. Ну и записи в объект может не быть. Сейчас у меня set сравнивает новое и старое устанавливаемое значение, не меняя собственно значение атома, чтобы определить нужно ли вызвать хендлер (https://github.com/eigenmethod/mol/blob/master/atom/atom.ts#L139). И если хендлер не просто пишет в объект, а делает реквест, реконциляция здорово бы помогла при попытке проталкивания эквивалентного значения.

**Comment by zerkalica** [comment]
А почему с ignore сравнивается, а не с next?

**Comment by nin-jin** [comment]
Потому что next нужно сбрасывать после любого пуша, иначе хендлер даже при затягивании будет вызываться со значением. А ignore - лишь после пуша вследствии не вследствии проталкивания, чтобы игнорировать два одинаковых проталкивания подряд, но если между ними встрянет что-то ещё - уже не игнорировать.

**Comment by zerkalica** [comment]
Да _next не нужен просто, это говнокод, его достаточно пробрасывать до хэндлера как аргумент.
А ignore скорее всего можно было решить, добавив еще один статус, подумать надо.

**Comment by nin-jin** [comment]
> Да _next не нужен просто, это говнокод, его достаточно пробрасывать до хэндлера как аргумент.

При перезапуске хендлера этот аргумент нужно откуда-то брать. Иначе незавершённое проталкивание вдруг превратится в затягивание.

> А ignore скорее всего можно было решить, добавив еще один статус, подумать надо.

Так надо ведь не любое значение игнорировать, а лишь эквивалентное тому, что последнее проталкивалось, но только если оно после этого не изменилось иным способом (затягивание, прямая установка в кеш).

**Comment by zerkalica** [comment]
next это для связки set -> error -> get -> set ?
Для retry что ли? Чтоб б последний set автоматом вызвался, если первый завершился неудачей?

Как все сложно, а ведь сколько еще неучтенных кейсов.

**Comment by nin-jin** [comment]
Например, допустим созданный коментарий надо добавлять в список вручную:

```
@ $mol_mem
post( post : string ) {

    // 1. Кинет $mol_atom_wait
    // 2. Вернёт объект комментария
    // 3. Вернёт тот же объект комментария ибо новое значение равно устанавливаемому
    const comment = this.api().comment_create( this.FormData() )

    // 2. Кинет $mol_atom_wait
    // 3. Отработает
    this.issue().comments().append( comment ).valueOf()

    // 3. Вернёт свежесозданный коментарий
    return comment
}
```

**Comment by zerkalica** [comment]
Я правильно понял, что next нужен только во время wait, что б при перезапусках отсечь первый set?

**Comment by nin-jin** [comment]
next в post нужен, чтобы передать правильное значение, а ignore в comment_create, чтобы его проигнорировать.

Вот такой глубокий реконцилер пока получился: https://github.com/eigenmethod/mol/tree/master/json/conform

**Comment by zerkalica** [comment]
Сценарий то какой с next? Что б просто значение передать, он не нужен.

Зачем ignore, если есть if( next_normal === this['value()'] ) return this.get() ?

**Comment by nin-jin** [comment]
Он нужен, чтобы оно не потерялось при перезапуске.

Сохранённое значение может быть не эквивалентно устанавливаемому. Ну пример с комментарием - мы посылаем патч, а возвращается нам все данные комментария.

**Comment by zerkalica** [comment]
Без сценариев или тестов нереально понять.

**Comment by nin-jin** [comment]
Добавил: https://github.com/eigenmethod/mol/commit/79a5a6d0c6cc85b8d044ebcac314aa41f61d3908

**Comment by nin-jin** [comment]
Также добавил поддержку циклических ссылок в $mol_json_conform и интегрировал его в $mol_atom. Производительность местами просела, местами возросла, но не сильно. Зато использовать стало удобнее и можно не бояться случаев, когда постоянно приходят развесистые json-ы отличающиеся в мелочах.

**Comment by zerkalica** [comment]
Для объектов, попробуйте такую вариацию, должно быть побыстрее:

```js
function shouldUpdate<Props: Object>(oldProps: Props, props: Props): boolean {
    if (oldProps === props) {
        return false
    }
    if ((!oldProps && props) || (!props && oldProps)) {
        return true
    }

    let lpKeys = 0
    for (let k in oldProps) {
        if (oldProps[k] !== props[k]) {
            return true
        }
        lpKeys++
    }
    for (let k in props) {
        lpKeys--
    }

    return lpKeys !== 0
}
```

**Comment by nin-jin** [comment]
> Для объектов, попробуйте такую вариацию, должно быть побыстрее

Попробую, спасибо.

> Вместо такого, лучше попробовать Map или Set и не создавать новую копию перед рекурсивным вызовом, а добавлять перед вызовом и удалять после.

Если у нас массив из 10 объектов, по 10 свойств с примитивами в каждом, то мой способ даст 10 созданий массивов и всё, а вариант с Set - 110 добавлений/удалений.

> Еще могут быть всякие RegExp, Date. 

Да их много может быть разных типов сравниваемых по содержимому. $mol_time_moment, например, нужно сравнивать по 7 полям из 8 и отдавать приоритет тому, у кого больше полей заполнено (чтобы кеш не терять).  Так что тут нужен способ объявлять кастомный компаратор для типа.

> Сразу return, не?

Не, остальные поля ведь тоже надо реконцилировать.

**Comment by zerkalica** [comment]
> Если у нас массив из 10 объектов, по 10 свойств с примитивами в каждом, то мой способ даст 10 созданий массивов и всё, а вариант с Set - 110 добавлений/удалений

Почему 110 то?
```js
if stack.has(t) return t
stack.add(t)
for ...
stack.delete(t)
```

``` stack.add(t) ``` будет столько же, сколько и ``` stack = [ ... stack , t ] ```
 
> Не, остальные поля ведь тоже надо реконцилировать.

Какая-то это тонкая дорожка. Vdom получается, только в профиль.

**Comment by zerkalica** [comment]
```js
		const tkeys = Object.keys( target )
		const skeys = Object.keys( source )
```

Забыли убрать из кода.

**Comment by nin-jin** [comment]
Действительно, сделал через Set.

vdom получится - это если на всё приложение будет один единственный атом :-)

**Comment by zerkalica** [comment]
> vdom получится - это если на всё приложение будет один единственный атом :-)

Не обязательно, в реакте каждый HOC со своим стейтом - это практически атом.

Разница в месте применения, тут vdom наверху, в данных, а в реакте внизу, в компонентах.

**Comment by nin-jin** [comment]
Ну, чем ближе к источнику данных, тем лучше. Ещё грязные проверки надо реализовать для тех кейсов, когда свойство меняется без бросания событий. Например, для отслеживания положения элемента на странице. Сейчас это делается через $mol_state_time.now(), что засирает логи по 60 записей в секунду.

Реализация стека через array оказалась быстрее.

**Comment by zerkalica** [comment]
В ``` $mol_conform_handler( Object ```, вместо второго for in можно в начале ``` let count = Object.keys(source).length ```, чуть быстрее, хотя несколько версий назад в хроме было не так.

**Comment by nin-jin** [comment]
Я думаю лучше без лишнего создания массива.

**Comment by zerkalica** [comment]
```js
		push( next_raw? : Value|Error ) : Value {
			if(!( next_raw instanceof $mol_atom_wait )) {
				this._ignore = this._next
				this._next = undefined
			}
```

В каких случая this._ignore будет отличаться от this._next здесь? 
Понятно, что когда сделали set, push, push. А в реальности это что за ситуация? В тестах она есть?

**Comment by nin-jin** [comment]
> А в реальности это что за ситуация? В тестах она есть?

Когда отработал set (с последующим пушем), а потом изменились зависимости и произошёл pull (с последующим пушем), например.
Сей тест покрывает этот случай: https://github.com/eigenmethod/mol/commit/79a5a6d0c6cc85b8d044ebcac314aa41f61d3908#diff-1522314779410741c41ce0995029df2fR177

> если this._ignore === this['value()']

А такое бывает?

**Comment by zerkalica** [comment]
> Сей тест покрывает этот случай

Разве? Там синхронная запись, ``` next_normal = $mol_conform( next , this['value()'] ) ``` достаточно для отсечки лишних ререндеров, зачем _ignore?

**Comment by nin-jin** [comment]
А какая разница синхронный или нет? там как раз и происходит set([666]) -> push([666]) -> push([777]).

**Comment by zerkalica** [comment]
Разница в том, что если выпилить ignore из кода, результат того теста не изменится. Т.е. ignore не покрыт кодом.

**Comment by nin-jin** [comment]
У меня падает при выпиливании

```
			let next_normal = $mol_conform( next , this._ignore )
			if( next_normal === this._ignore ) return this.get()
```

**Comment by zerkalica** [comment]
Да, я не заметил ``` let val = { foo : [777] } ```, т.е. хэндлер отвергает предложенное значение и возвращает свое.

Но тогда, вот эти строки нелогичными выглядят:

```js
			atom.set({ foo : [666] })
 			$mol_assert_equal( called , 2 )
 			
 			atom.set({ foo : [666] })
 			$mol_assert_equal( called , 2 )
```

called === 3 должен быть во второй проверке.
Т.к. хз какая там логика будет в хэндлере, это он первый раз отверг значение и вернул старое, а во второй мог не отвергнуть. Зачем мы решаем это за него через ignore?

**Comment by nin-jin** [comment]
Нет, тут дело не во фреймах, а именно в том, чтобы предотвратить повторный вызов хендлера с тем же аргументом. Нормальные кейсы же: https://github.com/eigenmethod/mol/issues/277#issuecomment-336630475
Раньше set плохо продуман был, сейчас получше, хотя эти _next и _ignore сейчас выглядят как костыли. Будем продолжать думать и пробовать :-)

**Comment by zerkalica** [comment]
Так this['value()'] бы отсек, если бы не постоянный возврат ``` { foo : [777] } ```.
Со стороны логично, мы предложили значение, хэндлер послал нафиг, мы снова предложили - хэндлер опять послал нафиг.

А с ignore получается предложили второй раз, а до хэндлера не дойдет даже.

**Comment by nin-jin** [comment]
Хендлер не нафиг послал а запрос на сервер послал и записал ответ, который во многих случаях совершенно не равен тому, что мы передали. Бесконечно долбить сервер в надежде, что он пришлёт ровно то, что послали мы - контрпродуктивно.

**Comment by zerkalica** [comment]
а если это часть бизнес логики, что при повторной отсылке данных, придет новая копия или еще что?

**Comment by nin-jin** [comment]
Ну, рандомизировать запрос, если что - вообще не проблема.

**Comment by zerkalica** [comment]
Звучит как костыль, но я понял, отсечка важнее конечно.

Просто принятая абстракция атомов решает много проблем, но и создает не мало тоже.

**Comment by nin-jin** [comment]
Кроме рандомизации можно сделать поддержку force для set. Тогда force будет действовать единообразно - принудительно вызывать хэндлер. А в кэш писать каким-то иным способом. Я склоняюсь к такому:

```
@ $mol_mem
data() {
    const atom = $mol_atom_current()
    setTimeout( ()=> atom.push({ foo : 'bar' }) , 1000 )
    throw new $mol_atom_wait
}
```

**Comment by zerkalica** [comment]
Может, кстати, потырить некоторые идеи с котлина?

https://kotlinlang.org/docs/reference/delegated-properties.html#observable

Там, old, new не стесняются прямо в обработчик кидать.
Я кстати в lom также делал по-началу.

**Comment by nin-jin** [comment]
У меня тоже так раньше было. Причём можно было передавать не просто новое значение, а патч:

```
foo.bar( [1,3] ) // установить значение
foo.bar( [2,3] , [3] ) // добавить 2 перед 3
foo.bar() // [1,2,3]
```

Но оказалось не очень востребовано. Хотя, может ещё вернусь к этому.

Сейчас $mol_mem является опциональной штукой, которую можно добавлять/удалять не меняя интерфейс. Если бы декораторы могли менять интерфейс (и TS это понимал), можно было бы передавать в хендлер что угодно.

**Comment by zerkalica** [comment]
а если после force добавить аргумент oldValue?

**Comment by nin-jin** [comment]
Тут ещё большой вопрос что считать oldValue - текущее состояние кеша или текущее значение get. Иногда нужно одно, иногда - другое.

**Comment by zerkalica** [comment]
Что такое текущее значение get? _next, имеется в виду?

**Comment by nin-jin** [comment]
То, что вернёт get. Rti-nj bpyfxfkmyj gecnjq/

**Comment by zerkalica** [comment]
Переделал на conform, в качестве значения попробовал реактовый элемент сохранить и получил exception:

```
Uncaught TypeError: Cannot assign to read only property '$$typeof' of object '#<Object>
```

Пришлось лепить костыль, исключать элементы из conform. Но точно это нормально мутабельно модифицировать старый объект в conform? Могут быть разные ситуации для push.

**Comment by nin-jin** [comment]
Можно просто создавать новый объект, да. Но тогда будет проблема с циклическими ссылками.

**Comment by zerkalica** [comment]
Скорее всего normalize придется прокидывать из декоратора в исключительных случаях. Так себе решение.

Просто нельзя считать все объекты, приходящие в push, простыми деревьями, нужно ограничение глубины.

**Comment by zerkalica** [comment]
А если нельзя читать объект вглубь? Как в read-only, например

**Comment by nin-jin** [comment]
В read-only читать всё же можно :-)

**Comment by zerkalica** [comment]
Читать да, писать никак.
Но читать нельзя прокси, на манер вашей обработки ошибок, много нюансов есть.

**Comment by nin-jin** [comment]
Ну так вы можете не писать, а создавать новую структуру - в неё-то писать можно будет.

Прокси с ошибкой упадёт - это ж хорошо.

**Comment by zerkalica** [comment]
В том то и дело, не я создаю, а React.createElement, пока не очень понятно, но возникает ситуация, когда таже структура возвращается.

**Comment by nin-jin** [comment]
Добавил кеширование, чтобы не сравнивать одно и то же по 10 раз: https://github.com/eigenmethod/mol/commit/259bf3f2e2832c8d7de371433b10011b58a7a753

Например, приходит нам развесистый JSON, мы его сохраняем в атом. JSON реконцилируется, всё хорошо. Но вложенный компонент может зависеть лишь от одной ветки исходного JSON. И если он её кеширует через атом, если эта ветка поменялась, то он повторно попытается её реконцилировать. Чтобы этого не происходило - возвращаем target, если эти два target и source уже реконцилировали.

**Comment by zerkalica** [comment]
Профит то оно какой дает? Ускорилось сильно?

**Comment by nin-jin** [comment]
Не сильно. Во многом от данных зависит.
