### ISSUE TITLE
Ошибка в консоли

### ISSUE THREAD

**Issue by vladknp** [eigenmethod/mol#279]
Выполнил согласно [Quick start](https://github.com/eigenmethod/mol#quick-start)
+ добавил тесты из [видео](https://youtu.be/PyK3if5sgN0?t=167), которые к стати в быстром старте отсутсвуют

В консоли вывело сообщение http://take.ms/vnhRI

**Comment by nin-jin** [comment]
Судя по ошибке GIT добавим файлам виндовые переводы строк. Вы точно исполняли эту команду до клонирования?

```
git config --global core.autocrlf input
```

**Comment by nin-jin** [comment]
Добавил тесты в QuickStart.

**Comment by vladknp** [comment]
> Вы точно исполняли эту команду до клонирования?

> git config --global core.autocrlf input

Нет, вот эту комманду не делал.
Только что выполнил, так сказать на будущее.

Вручную в редакторе поменять crlf на lf и повторно вставить код my_hello.view.tree. Перезапустил сборщик. Но ничего не изменилось.
Удалил dirs "mom", "node", "my/hello/-view.tree" (который сотадется при npm start), после выполнил "npm install", "npm run". В результате выполненых действий все заработало. Поллагаю что удаление каталога "mom" было излишним но на всяк случай сделал это.

Спасибо за подсказку.

**Comment by nin-jin** [comment]
Нет, всё правильно, нужно было переклонировать `mol`, чтобы гит выкачал исходники справильными переводами строк.
