### ISSUE TITLE
Мостик к React

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#281]
Допустим, есть приложение на реакте, которое надо постепенно перевести на mol.
Не думали, как можно сделать это плавно, не сильно меняя экосистему сборки? Как минимум, что б новые компоненты на mol для реакта адаптировать. Этакий мостик между react и mol.

**Comment by nin-jin** [comment]
Это ещё смотря какая система сборки используется.

**Comment by zerkalica** [comment]
Пока можно на уровне параллельной сборки. Пересборка библиотеки mol-bundle запущена в фоне через watch.

```js
import mol from 'mol-bundle'

function MyOldReactComponent({some}) {
  return <mol.mol_string value={some}  />
}
```

Если такого добиться, плагин к вебпаку это уже дело техники.
Вам бы еще от mam мостик к npm. Самое простое - написать скрипт, который последний снапшот мола пакетирует.

Вы б накидали какой roadmap.
