### ISSUE TITLE
Add generator for Yeoman

### ISSUE THREAD

**Issue by weekens** [eigenmethod/mol#282]
It would be nice to have a hello-world generator for $mol in [Yeoman](http://yeoman.io).

**Comment by nin-jin** [comment]
You can simply start dev server and open hello-world at localhost:8080/mol/app/hello (sourses at mol/app/hello in mam-project root)

**Comment by nin-jin** [comment]
Короче, кодогенераторы мы не поощряем. Поэтому старт нового проекта в [MAM](https://github.com/eigenmethod/mam) реализован так, что проще создать файл и начать писать код, чем запускать генератор и отвечать на все его вопросы.
