### ISSUE TITLE
css-in-js

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#283]
Фейсбуковцы сделали html-in-js, но не захотели внедрять css-in-js и стандарт CSSX.

У вас в презентации, в главе [Что не так с HTML?](https://github.com/nin-jin/slides/tree/master/mol#Что-не-так-с-html) есть  такие слова:

> Если программист оперирует компонентами, а браузер JS и DOM объектами, то зачем нам эта мимикрия под HTML, 

Вы, в отличие от фейсбуковцев, не боитесь заглядывать за горизонт и бежать впереди поровоза, так почему вы не сказали того же для css и продолжаете работать с селекторами, билдить здоровенный css для всего приложения?

Если программист оперирует компонентами, а браузер JS и DOM объектами, то зачем нам эта мимикрия под CSS? 

Селекторы и css - атавизм эпохи документного html. В js есть композиция, наследование, реактивность, типы в ts/flow. В css добавили возможность анимации делать и недавно переменные завезли, вау, осталось импорты нормальные сделать, а не эмуляцию require, добавить типы, классы, computable-значения и т.д.

Я пытаюсь экспериментировать с css-in-js и DI:
Вот пример [cssChange](https://github.com/zerkalica/rdi-examples/blob/master/src/examples/cssChange.js) - реактивного изменения css в сервисе.

```js
class Store {
    @mem red = 140
}

class CssChangeTheme {
    _store: Store

    constructor(store: Store) {
        this._store = store
    }

    @mem @theme.self get css() {
        const store = this._store
        return {
            wrapper: {
                background: `rgb(${store.red}, 0, 0)`
            }
        }
    }
}
```

Это конечно сыро пока, но уже можно генерить стили реактивно или не реактивно, можно создавать стиль на каждый инстанс компонента, можно на тип, можно композировать с другими стилями. Реактивные стили живут только вместе с компонентами.

**Comment by nin-jin** [comment]
CSS имеет мощные возможности АОП. С помощью селекторов можно точечно изменить что угодно на любой глубине. На мой взгляд этих механизмов очень не хватает шаблонизаторам. Есть только умирающий XSLT и BEM-либы от Яндекса. Другое преимущество CSS - скорость. Хотя бы даже за счёт того, что стили не надо каждый раз устанавливать для каждого элемента. Ну и самое главное - CSS - отличный DSL для стилизации. Он специально для этого предназначался. HTML же никогда не предназначался для создания компонент. Если заменять CSS на генерацию стилей скриптами, то браузерные инструменты разработчика работы со стилями становятся неудобными: нельзя, например, для всех кнопок поменять отступы, или не понятно какие стили каким компонентом добавлены (сейчас это понятно по имени класса).

С другой стороны JS даёт неимоверную гибкость и единообразную установку что динамических, что статических стилей. Я думал на тему генерации css из view.tree. Что-то типа:

```
$my_header $mol_view
    style *
        border \1px solid red
        background <= color_base \blue
        color <= color_base_text \white
```

```
[my_header] {
    border: 1px solid red;
}
```

```
style() {
    return {
        background : this.color_base() ,
        color : this.color_base_text() ,
    }
}
```

Но тут есть ещё следующие проблемы:

1. Нужен механизм примешивания значения свойства, а не просто переопределение, чтобы можно было вложенному компоненту добавить стилей, не стирая его собственные. В принципе это полезная фича и для других случаев, но как её органично вписать в текущую концепцию с настройкой через переопределение я затрудняюсь сказать.
2. Некоторые свойства обрабатываются по особому. Можно ввести спец синтаксис именно для стилей:

```
$my_header $mol_view
    @style
        border \1px solid red
        background <= color_base \blue
        color <= color_base_text \white
    sub /
        <= Title $mol_view
            @style
                 fontWeight \bold
```

Но остаётся вопрос как стилизовать подкомпонент подкомпонента. Тут уже нужны будут селекторы... и получится тот же CSS, но велосипедный и без каких-либо существенных преимуществ.

**Comment by zerkalica** [comment]
Для чего что-то стилизовать отдельно в компонентной верстке. Для чего вообще это понятие нужно в  компонентах?

Стили - это такая же внутренняя деталь компонента, как и любые другие свойства, разве нет?
Селекторы, разве не костыль из мохнатых времен, когда нужно было расшарить куски css между элементами без копипаста, поэтому ввели абстракцию - селектор?

> Если заменять CSS на генерацию стилей скриптами, то браузерные инструменты разработчика работы со стилями становятся неудобными: нельзя, например, для всех кнопок поменять отступы, или не понятно какие стили каким компонентом добавлены (сейчас это понятно по имени класса).

В jss пока нет, но в теории также можно генерить понятные имена, по контексту использования, это никак не ограничение css-in-js. Для кнопок будет сгенерен один стиль, с именем этой кнопки,

> Но остаётся вопрос как стилизовать подкомпонент подкомпонента.

А что это значит, там конвеншены какие-то? Разве ваш tree, с его переопределяемостью, нелья применить к стилям?

**Comment by nin-jin** [comment]
Ну вот последний пример. Есть календарик, есть датепикер.

```
$mol_date $mol_view
    Calendar $mol_calendar
```

```
$mol_calendar $mol_view
    Day!day $mol_view
```

Нужно стилизовать дни в календарике, который находится в датепикере. Как это сделать?

В CSS это делается через селектор с каскадом:

```
[mol_date_calendar_day] { ... }
```

Как это адекватно сделать через css-in-js?

**Comment by zerkalica** [comment]
Так, например
```
$mol_date $mol_view
    Calendar $mol_calendar
      day
        @style bla-bla
```
```
$mol_calendar $mol_view
    @style bla
    Day!day $mol_view
```

сгенерятся 2 класса: mol_calendar и mol_date_calendar_day.  Переопределение вглубь, с учетом иерархии.

**Comment by nin-jin** [comment]
Мне видится лишь такой вариант:

```
$mol_date $mol_view
    Calendar %
        Day!id %
            @style %
                color \red
```

Где % обозначает примешивание. Ну и как-то через контексты видимо свойства каждого компонента должны собираться воедино.

**Comment by zerkalica** [comment]
Можно сделать пока первый шаг, не собирать свойства через контексты и генерить css как и раньше -
 статически. Отличия в автоматизации, не надо самому генерить составные имена классов вроде mol_date_calendar_day.

tree начинает patch, sed, ed и пр. напоминать, команды редактору - переместить курсор на 3ю позицию и вставить xyz. =)

**Comment by nin-jin** [comment]
> не надо самому генерить составные имена классов

Их и так не обязательно руками генерить - можно брать сгенерированные из дома.

Не хотелось бы view.tree переусложнять специальными кейсами, иначе в нём совсем сложно будет разобраться.

**Comment by zerkalica** [comment]
mol_date_calendar_day - если что переопределить, надо явно прописать в css, разве нет?
А если day поменяется на myDay, как автоматически выявить, что надо отрефачить.

**Comment by nin-jin** [comment]
Надо. И по этому имени легко найти место определения стилей.
Да, с рефакторингом беда.

**Comment by zerkalica** [comment]
По мне, так основная проблема не в css-in-js, а в синтаксисе tree, возможность наряду с css клепать стили в компоненте были бы кстати.

**Comment by nin-jin** [comment]
Ну и скрипты уж заодно :-) Всё же основное назначение view.tree - композиция компонент. Стили и поведение будут лишь мешаться.

**Comment by zerkalica** [comment]
Никак не пойму, почему вы разделяете понятия стили и компонент - это одна цельная хрень.
Всякие селекторы по бему притянуты за уши.

**Comment by nin-jin** [comment]
Я разделяю стили и композицию. Они предназначены для разных вещей, с ними работают в разное время, бывает даже ответственны за них разные люди. А вместе они образуют один компонент, да. Но компонент - это не файл, а директория с файлами. Разные файлы описывают разные аспекты компонента.

**Comment by nin-jin** [comment]
Допустим у нас такие 3 компонента:
```
$mol_calendar $mol_view
    Day!day $mol_view
        style %
            border \1px solid red

$mol_date $mol_view
    Calendar $mol_calendar

$my_date $mol_date
    Calendar %
        Day!day %
            style %
                background \red
            kids / <= day_text!day \ 
```

Из последнего можно сгенерировать такой css:

```
[mol_calendar_day] {
    border: 1px solid red;
}

[my_date_calendar_day] {
    background: red;
}
```

А для биндингов соответственно ренерить такого рода код:

```
Calendar() {
    return $mol_patch( super.Calendar() , orig => ({
        Day : day => $mol_patch( orig.Day( day ) , orig => ({
            kids : ()=> [ this.day_text( day ) ]
        }) )
    }) )
}
```
