### ISSUE TITLE
Uncaught Error в todomvc benchmark 

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#284]
[todomvc bench](http://mol.js.org/app/bench/#bench=http:%2F%2Feigenmethod.github.io%2Ftodomvc%2Fbenchmark%2F#sample=angular2%7Eangularjs%7Eknockoutjs%7Emol%7Epolymer%7Ereact-alt%7Evanillajs%7Evue#sort=fill#)

При удалении todo вылезает:

```
Uncaught Error: Running fill,angular2,[object Object]..
at new $mol_atom_wait 
...
```

**Comment by nin-jin** [comment]
Починил. Дело в том, что возвращаемый прокси с ошибкой, json и когда этот  json пушился - conform приводил к всплытию ошибки, что обламывало пуш. А ошибки перехватываются сейчас лишь при pull. Добавил проверку в conform, чтобы он не сравнивал ошибки. Когда буду объединять actualize и value скорее всего внесу push под try-catch.

**Comment by zerkalica** [comment]
```js
let next = ( next_raw instanceof Error || prev instanceof Error ) ? next_raw : $mol_conform( next_raw , prev )
```

Разве в push не должно отсекать такие случаи?

**Comment by nin-jin** [comment]
Такой не отсекает:
```
next = { foo : proxy_error }
```
