### ISSUE TITLE
demo $mol_app_files_demo does not work in Firefox 52.4.0 (32-bit), Windows XP

### ISSUE THREAD

**Issue by AlexRadch** [eigenmethod/mol#287]
$mol_app_files_demo does not work in Firefox 52.4.0 (32-bit), Windows XP. 
It returns `Unknown HTTP error`.

![screenshot_1](https://user-images.githubusercontent.com/6407980/32645091-052016de-c618-11e7-89ce-fa7b59bde894.png)

Can you test $mol_app_files_demo in all modern browsers?

**Comment by zerkalica** [comment]
May be uBlock, adblock or same? Try without it.

**Comment by nin-jin** [comment]
Вот такое вот чудесное правило:

```
/\:\/\/[a-z0-9]{5,}\.com\/[A-Za-z0-9]{3,}\/$/$script,stylesheet,third-party,xmlhttprequest
RuAdList+EasyList
```

**Comment by AlexRadch** [comment]
Yes it is AdBlock issue.  Send report to adBlock.
