### ISSUE TITLE
$mol_app_signup_demo: Два сообщения об ошибках пишутся слитно

### ISSUE THREAD

**Issue by AlexRadch** [eigenmethod/mol#294]
Если в поле ввода сделать две ошибки то сообщения об ошибках не разделяются между собой:

![screenshot_3](https://user-images.githubusercontent.com/6407980/32768797-f71c9954-c94b-11e7-9abd-7049f109bf92.png)

**Comment by nin-jin** [comment]
Раньше там был большой отступ. Думаю а стоит ли показывать все ошибки? Возможно стоит показывать только одну, самую актуальную.

**Comment by AlexRadch** [comment]
Разделите точкой с пробелом.

**Comment by nin-jin** [comment]
Сделал, чтобы сообщение выводилось только одно. На мой взгляд не стоит вывалить нна пользователя 100500 сообщений, а лишь то, что ему нужно сделать непосредственно сейчас. Кому потребуется - будет выводить несколько сообщений или даже целых блоков.
