### ISSUE TITLE
$mol_app_quine_demo: написана неверно по определению!

### ISSUE THREAD

**Issue by AlexRadch** [eigenmethod/mol#296]
Программы, использующие внешние данные (чтение текста программы из файла, ввод его с клавиатуры и так далее), куайнами не считаются.

Или перепишите или переименуйте или удалите.

**Comment by nin-jin** [comment]
Так то и не квайн, а $mol_app_quine :-)

**Comment by nin-jin** [comment]
У вас есть идеи как назвать это приложение лучше, чтобы было понятно, что оно выводит собственные исходные коды?
