### ISSUE TITLE
Demo: URL параметры из одной демо программы передаются в другую демо программу

### ISSUE THREAD

**Issue by AlexRadch** [eigenmethod/mol#299]
1. Зайдите в демо программу $mol_app_lamps_demo и выберите первую лампу. URL станет следующим http://mol.js.org/app/demo/#demo=mol_app_lamps_demo/lamp=1.
2. Перейдите в другую демо программу выбрав ее в меню слева. Например выберите Hello.

Строка URL станет http://mol.js.org/app/demo/#demo=mol_app_hello_demo/lamp=1. В ней сохраниться параметр `/lamp=1`.

Строка URL должна поменяться на http://mol.js.org/app/demo/#demo=mol_app_hello_demo без параметра `/lamp=1`.

**Comment by wmakeev** [comment]
Насколько я помню, Дмитрий, вы говорили что это тоже фича. Хотя, замечу, не очевидная.

**Comment by nin-jin** [comment]
Да, фича, позволяет при переключении между видами сохранять параметры. Но в демо-приложении она действительно не нужна.

**Comment by nin-jin** [comment]
Проблема не актуальна, так как демо приложения вынесены сюда: https://showcase.hyoo.ru/
