### ISSUE TITLE
Visual design concept

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#3]
Нужно продумать следующие вещи..

# Адаптивная раскладка
* Как задаются размеры.
* Как размеры адаптируются под размер родительского блока.
* Как меняется раскладка блоков в зависимости от размера родительского блока.

Можно пощупать пример адаптации под размер: http://nin-jin.github.io/form/

# Стилизация
* Какие формулы вычисления цвета используем (цветовая схема, сколько цветов, правила для цветов линий, шрифтов, цвета при наведении/фокусе, цвета для выключенного функционала).
* Как задаются базовые константы (базовый цвет, акцентный цвет, гамма, фоновое изображение).

Можно пощупать пример перекраски интерфейса под базовый цвет: http://nin-jin.github.io/friends/
Через консоль разработчика можно задать другие цвета и даже изображение.

# Шрифты
* Какой набор шрифтов используем.
* Какие размеры, как изменяем их в зависимости от назначения или размеров родительского блока.

Желательно использовать стандартные шрифты, но они разные в разных системах - это стоит иметь ввиду.

# Конкуренты

* http://getbootstrap.com/components/
* http://foundation.zurb.com/apps/docs/#!/forms
* http://www.telerik.com/kendo-ui/autocomplete
* http://examples.sencha.com/extjs/6.0.2/examples/admin-dashboard/#dashboard
* https://sapui5.hana.ondemand.com/explored.html#/sample/sap.ui.layout.sample.GridTasks/preview

**Comment by ksusharimm** [comment]
**Стилизация**

Цвет фона белый.
В итоге определились, что даем пользователю возможность кастомизировать один акцентный цвет, который будет использоваться в ряде компонентов (кнопках, иконках и т.д.). Так как вне зависимости от яркости выбранного акцентного цвета шрифт на нем должен читаться, для пользователя будет возможность также переключить цвет шрифта между белым и черным. В этом случае цвет шрифта будет меняться только в компонентах акцентного цвета с прозрачностью не более 50%. 
Также будет возможность откатить кастомизацию до цветов по умолчанию.

Цветовая схема для графиков будет строиться следующим образом:
Каждый последующий цвет выбирается на цветовом круге как контрастный по отношению к имеющимся цветам. За "нулевой" цвет берется акцентный (поставленный по умолчанию или кастомизированный пользователем), далее по порядку контрастные по указанной схеме. Эта схема работает только для цветового тона. Для того, чтобы выбранные таким образом цвета сочетались, каждый последующий цвет также варьируется по насыщенности между 40% и 50% и по яркости между 55% и 85%.

При наведении курсора на цветной кликабельный элемент графика, его яркость понижается на 20%.

**Comment by ksusharimm** [comment]
При выделении у столбиков появляется обводка по центру, цвет 131C38, толщина 2, пунктирная, округлая, длина линий 8 px для разрешения 1366x768, промежутки между линиями длиной в 6 px. Если выделена линия, а не столбик, то же самое – пунктир с длиной в 8px и промежутками в 6 px, цвет 131C38, толщина такая же как у линии. Таким образом, в промежутках должен быть виден цвет линии. Пример скидываю. Такой цвет выбран потому, что он гораздо темнее любого из цветов графиков, и этот цвет будет использоваться как дополнительный к акцентному (он будет фоном для шапки или боковой панели). 
Можно ли анимировать пунктирное выделение чтобы оно двигалось по кругу? Так среди множества элементов графика выделенный элемент не потеряется.

![screen shot 2016-05-18 at 12 33 34](https://cloud.githubusercontent.com/assets/19321145/15354161/6011deb2-1cfd-11e6-8f92-148921281056.png)
![screen shot 2016-05-18 at 12 33 54](https://cloud.githubusercontent.com/assets/19321145/15354163/602e8b16-1cfd-11e6-830f-2bdd2b5e3f5b.png)
![screen shot 2016-05-18 at 12 34 12](https://cloud.githubusercontent.com/assets/19321145/15354164/6057b70c-1cfd-11e6-9bf1-87f89614a7b9.png)

**Comment by nin-jin** [comment]
Конкретно по графикам пишем сюда: https://github.com/eigenmethod/mol/issues/2
А тут общие концепции, принципы по которым будем разрабатывать компоненты.

**Comment by ksusharimm** [comment]
**upd**
Так как одним из компонентов будут белые поля ввода текста, берем цвет фона ECECF3. 
Шапка приложения будет окрашиваться в фирменный цвет компании, который далее используется как акцентный на странице. Назовем его цвет Х (далее это потребуется для объяснения формулы выбора цвета).
Если к шапке должна будет добавиться вторая шапка, она будет такого же цвета, то есть цвета X, и между ними будет разделитель цвета шрифта на этом фоне (так как шрифт может быть либо темным, либо светлым в зависимости от цвета Х) с полупрозрачностью 50%. Пример скидываю.
Основной сайд-бар будет цвета 2F3955, который не будет участвовать в графиках. В случае, если со строки сайд-бара необходимо перейти на второй сайд-бар, то следующий будет такого же цвета, как фон, то есть ECECF3. Пример прикладываю.

![1366x768](https://cloud.githubusercontent.com/assets/19321145/15392957/7e2026dc-1ddb-11e6-97f8-ba4c39d1a557.png)
![1366 768_2_header](https://cloud.githubusercontent.com/assets/19321145/15392958/8363c414-1ddb-11e6-83f7-7062ce49d857.png)
![1366x768_2_left_side](https://cloud.githubusercontent.com/assets/19321145/15392960/8615ceaa-1ddb-11e6-9dca-892396251e3a.png)


**Данные для формулы вычисления цвета шрифта**
За акцентный цвет берем фирменный цвет компании, он же цвет Х, и его показатели H, S и B.
1. Если (S + B) > 17, при этом (S - B) < 10, цвет X слишком яркий для того, чтобы располагать на нем шрифт любого цвета. Если выполняется это условие, то значение S нужно уменьшить до такого значения, чтобы выполнялось правило (S + B) < 17, при этом (S - B) < 10. Измененный цвет X будет почти такого же оттенка, однако будет приятнее глазу.
2. Если (S + B) > 17, при этом (S - B) < 10, цвет Х остается без изменений, а шрифт подбираем по следующим правилам:
2.1. При B < 80 шрифт белого цвета.
2.2. При S < 45 и B > 80 шрифт будет цвета Х со значением B меньше на 60%.
2.3. При S > 45 и B > 80, начинается самое интересное :) Если оба этих показателя увеличиваются, то черный шрифт будет использоваться при H от 30 до 195 при S = 45 и B = 80, а при H от 0 до 30 и от 195 до 360 будет использоваться белый цвет. При увеличении показателй S и B показатель H для белого шрифта будет стремиться к нулю, то есть чем больше S и B, тем меньше белого шрифта будет использоваться, пропорционально от H = 30 от H = 195. Если непонятно, иллюстрирую примером.

Можно ли использовать эти данные, чтобы построить формулу?

**Comment by ksusharimm** [comment]
**upd**
Цвет фона белый.
Фирменный цвет X на примере показан в квадрате внутри артбордов. 
H фирменного цвета остается неизменным.
Для верхней панели S = 50, B = 80.
Для сайд-бара S = 10, B = 95.
Для чекбокса, радио-баттонов и свитчеров цвет активной заливки S = 60, B = 90.
Второй сайдбар, выходящий из строки первого, S = 4, B = 98.
Примеры с двумя крайними цветами и одним обычным скидываю.
![1366x768_06](https://cloud.githubusercontent.com/assets/19321145/15397426/41ef9c86-1df1-11e6-8290-77ad17d1114e.png)
![1366x768_05](https://cloud.githubusercontent.com/assets/19321145/15397452/4ec34598-1df1-11e6-94c1-0f5add875d11.png)
![1366x768_04](https://cloud.githubusercontent.com/assets/19321145/15397447/4d909ed2-1df1-11e6-8804-ef1b04471db9.png)
![1366x768_03](https://cloud.githubusercontent.com/assets/19321145/15397449/4e3b09da-1df1-11e6-8257-361e2fcc6018.png)
![1366x768_02](https://cloud.githubusercontent.com/assets/19321145/15397448/4e398a06-1df1-11e6-9fe3-2e9a51788535.png)
![screen shot 2016-05-19 at 17 38 47](https://cloud.githubusercontent.com/assets/19321145/15397451/4e85558a-1df1-11e6-837e-47440a8fff7b.png)

**Comment by nin-jin** [comment]
Текущие договорённости:
1.	Цвета интерфейса приложения будут строиться от базового цвета по формулам.
2.	Базовый цвет задаётся дизайнером и вносится разработчиком.
3.	Попробуем два варианта подбора цветов для графиков:
3.1.	По формулам относительно базового цвета.
3.2.	Предопределённая дизайнером фиксированная палитра на 16 цветов. При выводе большего числа графиков, считаем, что пользователь не должен ожидать, что все цвета будут различимы и просто повторяем цвета из палитры.

**Comment by nin-jin** [comment]
Предлагаю следующие правила:

1. Базовый размер шрифта: 12pt.
1. Семейство шрифтов: 'Segoe UI', Frutiger, 'Frutiger Linotype', 'Dejavu Sans', 'Helvetica Neue', Arial, sans-serif
1. Высота линии: 1.5
1. Отступы задаём в vmin.
1. Размеры шрифтов в rem.
1. Размеры скруглений в rem.
1. Ограничения на размеры в rem.

vmin - 1% от минимума из ширины и высоты окна браузера.
rem - базовый размер шрифта.

**Comment by nin-jin** [comment]
От vmin пришлось отказаться в пользу rem, так как субпиксельные размеры вызывают косяки рендеринга в Хроме.

Так как возражений не последовало, то считаю вопрос утверждённым.
