### ISSUE TITLE
$mol_state_arg: Why we are using hash based routing?

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#301]
**Hash based: `http://example.org/#product=123/order`**

- One more symbol
- Can not navigate to element by id

**Pseudo server: `http://example.org/product=123/order`**

- Server-side routing required
- Can not use static server
- Can not use CDN
- Can not use in Cordova
- HTML сache littering

**Comment by punkkk** [comment]
Best discussion ever.
