### ISSUE TITLE
Design patterns

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#305]
# SOLID

## Single responsibility

MAM поощряет создание маленьких модулей - работать с ними легко и просто. Это предотвращает кучкование множества ответственностей в одном месте.

## Open/Closed

MAM ориентирована на отсутствие версионирования модулей. Любой модуль открыт для расширения интерфейса, но закрыт для изменения интерфейса. Это позволяет безбоязненно обновлять модули до самых актуальных версий и переезжать на другие модули постепенно.

## Liskov substitution

В $mol активно используется наследование, которое даёт реализации интерфейса по умолчанию. Переопределять методы предка стоит лишь так, чтобы не нарушать его контракт.

## Interface segregation

Этот принцип применим лишь к номинативной типизации, а в TypeScript реализована структурная типизация, которой данный принцип не нужен.

## Dependency Inversion

У каждого объекта-контейнера есть свойство `$`, представляющее собой реализацию Ambient Context. Если объект получает зависимости через это свойство, то любая его зависимость может быть переопределена владельцем, владельцем владельца и тд. По умолчанию, контекст объекта не имеющего владельца равен глобальному контексту среды исполнения.

**Comment by zerkalica** [comment]
Лучше описать как mol помогает SOLID. Например:
S - авто-импорты помогают дешевле дробить на модули
O - tree помогает дешево делать полностью открытые для расширения компоненты 
L - к mol не имеет отношения, просто придерживайтейсь его, т.к. наследования много
I - интерфейсов нет, а их роль как контрактов, лежит на дефолтных реализациях в ambient context-е
D - на основе паттерна ambient context, только без недостатков классического синглтон-подобного ac, т.е. присутствует в каждом классе и переопределяем в родителе для любых дочерних, реализация простая, соотвественно нет проблемы с многопоточностью

Хотелось бы не только плюсы но и минусы ac, с доказательством, что они не перевешивают плюсов.
