### ISSUE TITLE
Перехват Wait-исключений в родительских компонентах

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#310]
Бывает так, что нужно рендерить один индикатор на страницу. Нужно для этого случая предусмотреть ручки (аналог реактового Loading из 16.4).

Для компонент, дочерние компоненты которых рендерятся асинхронно (React) нужен способ перехватывать Wait/Error статус дочерних.

Сложность в сохранении дефолтного поведения, если наверху нет перехвата - внизу рисуется Loading...

На одном componentDidCatch такое поведение не сделать в реакте. Если бросить в render дочернего исключение, то родительский перехватит и отрисует индикатор, но без didCatch ошибка не будет обработана в дочернем.

**Comment by nin-jin** [comment]
И всё же что плохого в показе нескольких индикаторов по местам? Вот с общим индикатором есть следующие проблемы:
1. затрагивает большую площадь экрана, что даёт большее мерцание для взгляда. Блокируется весь экран из-за любой мелкой ерунды.
2. контролы, не зависящие от загружаемых данных могут стать недоступными. Вплоть до невозможности уйти со страницы, до таймаута.

**Comment by zerkalica** [comment]
Это ограничение в mol. В некоторых интерфейсах может быть плохо, когда куски экрана подгружаются последовательно, все дергается. Просто требования ui, заказчика.

**Comment by nin-jin** [comment]
Ну представим ситуацию - нажали на выпадушку и для загрузки вариантов пошёл запрос. Будем блокировать весь экран?

**Comment by zerkalica** [comment]
не, полное представление грузится также по клику на неполное представление. Разница только в том, что лоадер лучше "вписан" в неполное представление и его позицию можно задать любую.

Может быть так: слева список, справа - полное представление. При клике на элемент, именно в элементе появляется крутилка, а потом справа перерисовывается плашка.
 
В mol, на месте будущего полного представления, появляется плашка с полосками, а потом заполняется данными и это никак не изменить.

**Comment by nin-jin** [comment]
Если данные ещё не полностью прогружены, то справа мы не можем нарисовать всё. Получается либо мы должны нарисовать абы как (криво), либо дождаться полной загрузки данных, либо таки нарисовать индикатор и справа.

**Comment by zerkalica** [comment]
Что б было понятнее о чем речь - https://www.youtube.com/watch?v=v6iR3Zk4oDY&t=1538
