### ISSUE TITLE
PascalCase camelCase kebab-case snake_case

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#312]
# PascalCase

- Традиционно используются для имён классов
- ТРебуется много нажатий шифта вовремя
- СлипшиесяСловаТрудноЧитать
- Проблемы с аббревиатурами: XMLHttpRequest
- Одноимённые имена файлов могут вызвать проблемы в не чувствительных к регистру файловых системах
- Имеет проблемы с наложение стилей в CSS (в зависимости от типа элемента и типа селектора стиль может не примениться)

# camelCase

- Традиционно используются в именах переменных и полей
- ТРебуется много нажатий шифта вовремя
- слипшиесяСловаТрудноЧитать
- Проблемы с аббревиатурами: mxBADownload
- Имеет проблемы с наложение стилей в CSS (в зависимости от типа элемента и типа селектора стиль может не примениться)

# kebab-case

- Традиционно используются для имён в html, css, а также в именах файлов
- Редакторы не считают эти имена единым именем (выделение даблкликом, ctrl+стрелка и тп)
- Не допустимо в большинстве языков программирования

# snake_case

- Традиционно используются для имён  в "олдскульных" языках (C, C++, Rust)
- Требуется_много_нажатий_шифта

**Comment by punkkk** [comment]
Для кебаба редакторы настраиваются.

Проблемы с аббревиатурами ты надумал, давно уже принято делать так: MyXmlHtmlOrJson.
На счет слипшегося теста тоже надумано, это дело привычки, мне самецКейс читается очень ясно и удобно.

Обычно для имен файлов и директорий используем cebab-case, для кода Pascal + camelCase, стили - cebab.

**Comment by nin-jin** [comment]
http://yosefk.com/blog/ihatecamelcase.html
