### ISSUE TITLE
Результат на видео и в реальности отличается и глючный

### ISSUE THREAD

**Issue by gerchicov-bp** [eigenmethod/mol#313]
https://www.youtube.com/watch?v=PyK3if5sgN0

1)вы явно что-то делаете дополнительно, что не указано в видео - у меня сервер изменяется только при ручном перезапуске node.js, хотя по видео достаточно обновить страницу в браузере. Или может Atom чего-то делает, чего не делает visual studio code?
2)момент, когда после действий кнопка прыгает в центр экрана:
https://youtu.be/PyK3if5sgN0?t=2m26s
делаю те же действия - 0 эффекта. Ок, думаю, может код в readme изменился.
Вручную ввожу то, что было в файле .css на видео. Все равно 0 эффекта - текстовое поле находится вверху и занимает всю ширину окна.
Перезапускаю сервер еще раз - `npm start` - текстовое поле находится уже посередине, но все равно занимает всю ширину окна

**Comment by nin-jin** [comment]
1. Всё должно обновляться при перезагрузке страницы. Если вы используете Мак, то это может быть из-за низкого значения `ulimit` (ограничение на число одновременно открытых дескрипторов).

2. Стили немного поменялись с момента записи видео, да.

**Comment by gerchicov-bp** [comment]
1 - почему-то babel на том же маке умеет перезагружать страницы. Может стоит подключить его? Или хотя бы добавить инструкцию о том, как это сделать?
2 - стили поменялись - ок. Но почему если я пытаюсь повторить стили из видео, то получаю другой результат. У вас все нормально выглядит с последней версией библиотеки?

**Comment by nin-jin** [comment]
1. Так значит Мак? Попробую прикрутить https://github.com/paulmillr/chokidar
2. Просто добавьте своих стилей, чтобы получить, то, что вам нужно.

**Comment by nin-jin** [comment]
Попробуйте обновиться:
```
cd mam
git pull
cd mol
git pull
```

**Comment by gerchicov-bp** [comment]
1. попробую, спасибо
2. я недавно начал изучать node.js и хотел бы, чтобы страница выглядела как у вас в видео - маленькое текстовое поле посередине экрана, чего по каким-то причинам не происходит. Или я заметил что у вас yandex, а у меня chrome - и может быть в этом дело?

после обновления по-моему стало еще хуже (или осталось так же, но не проверял):
- обычный режим браузера - всегда отображается текстовое поле
- приватный режим браузера - всегда пустая страница
Пробовал стирать содержимое файлов `hello.view.tree` и `hello.view.css`, перезапускать сервер - страница как будто закешировалась навсегда. При этом я обращаюсь именно к этому локальному серверу, потому что при его выключении браузер не находит index.html

**Comment by gerchicov-bp** [comment]
ок, проблему с css спишем на его незнание/другой браузер

да, действительно кеширование помогло. НО: я же не могу просить каждого пользователя отключить у себя кеширование? Тем более такая проблема обнаружилась только конкретно с этой библиотекой

**Comment by nin-jin** [comment]
На продакшен сервере кешированием управляют через http заголовки. Например, гитхаб устанавливает кеширование на 10 минут: `Cache-Control: max-age=600`.
