### ISSUE TITLE
Некорректная реакция на сочетание правого и левого биндингов с дефолтным значением

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#326]
```
<= Axle_list $mpk_tss_reports_axle_list
      axle_current => axle_current
    <= Axle_chart $mpk_tss_reports_axle_chart
      axle <= axle_current null
```
Компилятор tree должен кидать ексепшен, если встречается сочетания
` axle_current => axle_current ` и ` axle <= axle_current null `

**Comment by nin-jin** [comment]
Сделал, чтобы кидалось исключение. Заодно добавил в текст исключения информацию об обоих конфликтующих местах.

**Comment by zerkalica** [comment]
В tss работает.

Property already defined with another default value:
Logged_user null
