### ISSUE TITLE
Всё слиплось в $mol_string_demo

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#338]
Есть у нас демка строковых полей ввода: http://mol.js.org/app/demo/-/#demo=mol_string_demo

Но как-то они все послипались вместе. Надо бы добавить между ними воздуха, как в в аналогичной демке с редакторами кода: http://mol.js.org/app/demo/-/#demo=mol_textarea_demo

**Comment by Ne4to777** [comment]
Доработано
