### ISSUE TITLE
Сборка не восстанавливается после исправления ошибки

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#343]
Ветка feature/plot-optimize
1. Запустить, зайти на http://127.0.0.1:8080/mol/app/demo/-/#demo=mol_chart_demo_styles, открыть dev tools
2. В $mol_svg, с $mol_state_time.now() на $mol_state_time()
3. Обновить страницу, увидеть белую страницу, словить ошибку в консоли
4. В $mol_svg вернуть $mol_state_time.now()
5. Обновить страницу, увидеть белую страницу

**Comment by nin-jin** [comment]
Ага, воспроизвелось.

**Comment by nin-jin** [comment]
По ходу дела из-за ошибки сборщик отписывается от скомпилированных ts после сбойного, а тайпскрипт не пишет их снова, ибо они не менялись.

**Comment by nin-jin** [comment]
Поправил: https://github.com/eigenmethod/mol/commit/a047939ddb803e32cbd88299a1fd0d70de978f2e
