### ISSUE TITLE
$mol_app_bench: не отображаются страницы бенча и меню, лог чист

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#365]
После исправления #363 обнаружился баг

http://127.0.0.1:9080/mol/app/bench/index.html

![image](https://user-images.githubusercontent.com/274786/64420435-fc266000-d0a7-11e9-81c6-7ff1601bf8ba.png)

**Comment by nin-jin** [comment]
Там использовались хитрые манипуляции с реактивными свойствами. Надо подумать как реализовать то же поведение на новых атомах.

**Comment by zerkalica** [comment]
Вроде аналогичная проблема: #357
