### ISSUE TITLE
$mol_app_bench_geometry: белая страница

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#366]
в atom2 и в master, ошибок в консоли нет

http://mol.js.org/app/bench/geometry/

**Comment by nin-jin** [comment]
Там по идее должен быть редирект на интерфейс бенчмарка: http://mol.js.org/app/bench/#bench=geometry%2F#sort=render#

**Comment by zerkalica** [comment]
https://github.com/eigenmethod/mol/blob/master/app/bench/geometry/index.html

прям туда редирект пихать безусловный или как?

**Comment by nin-jin** [comment]
Агась, как в остальных бенчмарках. Сюда видимо забыл добавить.

**Comment by zerkalica** [comment]
Как-то странно все же хардкодить абсолютные урлы в модулях, пусть и в html

**Comment by nin-jin** [comment]
Идея в том, что ты даёшь ссылку на твой бенчмарк, а он открывает себя в интерфейсе. Сегодня в одном, завтра в другом.

**Comment by zerkalica** [comment]
Да, но все-равно хардкод, если я свой локальный форк хочу поднять?

**Comment by nin-jin** [comment]
Так а в чём проблема? Форкаешь и меняешь.

**Comment by nin-jin** [comment]
Зачем же закрывать несмерженную задачу?
