### ISSUE TITLE
$mol_app_inventory: Doubted while calculation, cordova.js 404

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#368]
http://127.0.0.1:9080/mol/app/inventory/

```
Doubted while calculation

$mol_app_inventory.Root["0"].dom_tree()
$mol_app_inventory.Root["0"].Enter().dom_tree()
$mol_app_inventory.Root["0"].Enter().dom_tree()/6:
```

![image](https://user-images.githubusercontent.com/274786/64422220-34c83880-d0ac-11e9-9764-4e018bfcb48e.png)

PS: Как-то подложить кордову, что б в сборку попадала.

PPS: Не атом версия, тоже не работает - http://mol.js.org/app/inventory/ белая страница и 404 на все скрипты

**Comment by zerkalica** [comment]
Может быть выпилить вообще это inventory

**Comment by nin-jin** [comment]
Похоже её сборка вообще отключена в travis.yaml
Да, я бы выпилил.

**Comment by nin-jin** [comment]
Выпилил.
