### ISSUE TITLE
$mol_app_studio: Не загружается отдельно

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#369]
Если просто открыть http://127.0.0.1:9080/mol/app/studio/ то будет ошибка

```
fetch.ts:19 GET http://127.0.0.1:8080/mol/app/studio/web.view.tree net::ERR_ABORTED 404 (Not Found)
(anonymous) @ fetch.ts:19
$mol_fiber_sync_wrapper @ fiber.ts:69
```
Заглушку надо вставить скорее всего.

![image](https://user-images.githubusercontent.com/274786/64423505-5d9dfd00-d0af-11e9-9f67-400d6aec1f00.png)

PS: в master http://mol.js.org/app/studio/ даже не загружаются скрипты

**Comment by nin-jin** [comment]
Надо просто $mol_view открывать на редактирование.

**Comment by zerkalica** [comment]
как это сделать то, если в урле нет параметров?

**Comment by nin-jin** [comment]
По умолчанию брать $mol_view.

**Comment by zerkalica** [comment]
Откуда брать то, его в бандле нет, хардкодить полный путь сорца чтоль?

**Comment by nin-jin** [comment]
Его не может не быть в бандле, это базовый компонент.

**Comment by zerkalica** [comment]
source=$mol_view указываю, редиректит на mol.view.tree и падает
![image](https://user-images.githubusercontent.com/274786/64439783-6c96a680-d0d3-11e9-9a7e-7128c10ad77d.png)

**Comment by nin-jin** [comment]
А, ну да, он объявлен без view.tree. По хорошему и его надо через view.tree  описать.

**Comment by zerkalica** [comment]
Не понимаю, что делать

**Comment by nin-jin** [comment]
Взять любой другой компонент. $mol_page может.

**Comment by zerkalica** [comment]
Studio пытается прочитать
http://127.0.0.1:8080/mol/app/studio/web.view.tree 

```
	@ $mol_mem
		classes_static() {
			const view_tree = '$mol_view $mol_object\n\ttitle \\\n\tsub /\n\tstyle *\n\tattr *\n\tevent *\n\tdom_name \\\n\n'
			const source = view_tree + $mol_http.resource( 'web.view.tree' ).text()
			return $mol_view_tree_classes( $mol_tree.fromString( source ) )
		}
```

**Comment by nin-jin** [comment]
Тогда странно, что не работает.

**Comment by zerkalica** [comment]
почему странно то, studio/-/web.view.tree нет никакого, я хз как там собираться должно, может в мету где добавить.

**Comment by nin-jin** [comment]
Всё генерится:
```
11:48:47 Built mol/app/studio/-/web.view.tree
```

**Comment by nin-jin** [comment]
Поправил в мастере.
