### ISSUE TITLE
$mol_app_request: Не отображается информация по запросам

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#372]
* При существующем URI, Запрос отправляется, но заголовки не отображаются.
* При изменении текста в URI в инпуте, запрос не отправляется.

![image](https://user-images.githubusercontent.com/274786/64426024-21ba6600-d0b6-11e9-84e2-85b96590db8a.png)

**Comment by zerkalica** [comment]
![image](https://user-images.githubusercontent.com/274786/67327810-339a8000-f521-11e9-99cd-b1dd4c60a652.png)

с выводом ошибок беда, так вроде норм

**Comment by nin-jin** [comment]
Не 2** ответы надо тоже нормально показывать, да.
