### ISSUE TITLE
$mol_build: Ускорение сборки

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#375]
Раньше в один поток собиралось медленно, на каждый чих по 30 сек.
Благодаря многопоточности сейчас где-то 10 сек на горячем старте, все-равно медленно.

Еще ощущение, что нет сейчас никакого инкрементального билда. Можно попробовать фишки 3.6 версии заюзать.

https://devblogs.microsoft.com/typescript/announcing-typescript-3-6-rc/

https://github.com/microsoft/TypeScript/pull/31432

TypeScript 3.6 now exposes two sets of APIs to operate on project references and incremental program building.

For creating --incremental builds, users can leverage the createIncrementalProgram and createIncrementalCompilerHost APIs. Users can also re-hydrate old program instances from .tsbuildinfo files generated by this API using the newly exposed readBuilderProgram

**Comment by nin-jin** [comment]
Не знаю откуда у тебя информация про многопоточность. Отрабатывает сборка синхронно.
Сейчас используется createWatchCompilerHost который сам ребилдит то, что считает нужным.

**Comment by zerkalica** [comment]
По загрузке процессора, раньше  ts никак не мог все ядра загрузить

**Comment by nin-jin** [comment]
Не факт, что это он их грузит. И не факт, что чем-то полезным.

**Comment by zerkalica** [comment]
Ускорить cold start тоже интересная задача. createWatchCompilerHost можно попробовать донастроить для incremental

**Comment by nin-jin** [comment]
А ты не хочешь попробовать сборщик переписать?

**Comment by zerkalica** [comment]
Сейчас норм, после твоего фикса тестового бандла и моего сорсмап-генератора
