### ISSUE TITLE
Поломано несколько ссылок

### ISSUE THREAD

**Issue by gituser3000** [eigenmethod/mol#400]
Сломана демка:
https://mol.js.org/app/demo/-/#demo=mol_nav_demo
ссылка из:
https://github.com/eigenmethod/mol/tree/master/nav

**Comment by gituser3000** [comment]
$mol_hyperhive - HypeHive API
тоже

**Comment by gituser3000** [comment]
https://github.com/eigenmethod/mol/tree/master/switch
сломана ссылка на демку

**Comment by gituser3000** [comment]
https://github.com/eigenmethod/mol/tree/master/cost
сломана ссылка на money_unit

**Comment by gituser3000** [comment]
на главной $mol_plot_fill ссылка
https://github.com/eigenmethod/mol/tree/master/plot/fil
вместо https://github.com/eigenmethod/mol/tree/master/plot/fill

**Comment by nin-jin** [comment]
Добавил демку для $mol_nav: https://mol.js.org/app/demo/-/#demo=mol_nav_demo
Удалил $mol_hyperhive ибо тот проект мёртв
Поправил ссылки.
