### ISSUE TITLE
Safari bugs

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#92]
- [x] Height 0 on single demo page
- [x] Broken keyboard events in suggester
- [x] Off scroll behavior in number component (if it disabled)

**Comment by ar2r13** [comment]
чекни ничего в ИЕ не поломалось

**Comment by nin-jin** [comment]
Рано её ещё закрывать, раз ещё не в мастере :-)

**Comment by nin-jin** [comment]
Не вижу пулреквеста.
