### ISSUE TITLE
Testing for crossplatforming of demos

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#94]
Необходимо протестировать следующие демки: https://eigenmethod.github.io/mol

В следующих окружениях:

- [x] Chrome последний.
- [x] Firefox последний.
- [ ] Edge последний.
- [x] IE 11.
- [ ] Safari на iOS9.
- [x] Стандартный браузер на Android 5.
- [ ] Cordova под Android 5.
- [ ] Cordova под iOS9.
- [ ] Cordova под Windows10.

**Comment by JulyJ** [comment]
**FireFox 50.1.0.**

- [ ] [$mol_app_bench_demo](https://eigenmethod.github.io/mol/#demo=mol_app_bench_demo). В отличии от Chrome в блоке есть скрол и отображение элементов отличается.
![selection_550](https://cloud.githubusercontent.com/assets/4419881/22200128/e0c6c1a4-e16e-11e6-9481-bdb17f755b07.png)
- [ ] Скролл на всех страницах работает очень медленно, а особенно это заметно на страницах с текстом, например[ $mol_app_habhub_demo](https://eigenmethod.github.io/mol/#demo=mol_app_habhub_demo).
- [ ] [$mol_app_inventory_controller_demo](https://eigenmethod.github.io/mol/#demo=mol_app_inventory_controller_demo). В поле, где можно ввести цифры в FF можно вводить любые символы, а в Chrome нет, только символ "e".
![selection_552](https://cloud.githubusercontent.com/assets/4419881/22200320/ac36dcfc-e16f-11e6-9aa1-2999833eb1b5.png)
- [ ] Не отображаются чекбоксы рядом с задачами в чеклисте.
![selection_557](https://cloud.githubusercontent.com/assets/4419881/22200314/a4bbc532-e16f-11e6-9bcd-509a21bb5f9e.png) [$mol_app_todomvc_demo](https://eigenmethod.github.io/mol/#supply=75BCD15#demo=mol_app_todomvc_demo)

**Comment by JulyJ** [comment]
**Chrome Version 55.0.2883.87 (64-bit)**
- [ ] В [$mol_app_taxon_demo](https://eigenmethod.github.io/mol/#supply=75BCD15#demo=mol_app_taxon_demo) появляется лишний элемент (без возможности expand), которого нет в FF.
![selection_564](https://cloud.githubusercontent.com/assets/4419881/22203848/03c482ac-e180-11e6-8dbf-3743620fa09f.png)

**Comment by JulyJ** [comment]
**Общие вопросы**

- [ ] [$mol_page_demo](https://eigenmethod.github.io/mol/#demo=mol_page_demo). Кнопка "Sign Up" активна, даже если она задисбалена (серая).
- [ ] [$mol_page_demo](https://eigenmethod.github.io/mol/#demo=mol_page_demo). Чекбокс "Shared" не срабатывает.
- [ ] [$mol_app_taxon_demo](https://eigenmethod.github.io/mol/#supply=75BCD15#demo=mol_app_taxon_demo). Таблица перестраивает свою ширину во время скролинга в зависимости от выводящегося на текущий содержимого.

**Comment by JulyJ** [comment]
Отчет о кроссбраузерности составленный с помощью BrowserStack: [crossbrowser.zip](https://github.com/eigenmethod/mol/files/732472/crossbrowser.zip):

**Comment by JulyJ** [comment]
Иттерация 2.
Демки http://mol.js.org/

- [ ]  Chrome последний.
- [ ]  Firefox последний.
- [ ]  Edge последний.
- [ ]  IE 11.
- [ ]  Safari на iOS9.
- [ ]  Стандартный браузер на Android 5.
- [ ]  Cordova под Android 5.
- [ ]  Cordova под iOS9.
- [ ]  Cordova под Windows10.

**Comment by nin-jin** [comment]
Задача устарела.
