### ISSUE TITLE
Single-handedly create the application

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#97]
Задача состоит в том, чтобы самостоятельно реализовать небольшое но полезное приложение. Желательно с интеграцией с HyperHyve.

Предварительно идея такая: приложение загружает и показывает список документов, по клику на название документа показывается его содержимое. Показываться оно должно через наш легковесный pdfer, который мы сможем встраивать и в другие приложения.

**Comment by nin-jin** [comment]
PDF, кстати, на мобилке не показывается.

**Comment by ar2r13** [comment]
Nexus 5X все показывает)

**Comment by nin-jin** [comment]
К сожалению, мало у кого есть Nexus 5X.

**Comment by ar2r13** [comment]
Ну тогда все таки нужен парсер .pdf

**Comment by nin-jin** [comment]
Почитал я спеки - ну нафиг. Лучше на сервере рендерить и картинки показывать.
