### ISSUE TITLE
$mol_split

### ISSUE THREAD

**Issue by ar2r13** [eigenmethod/mol#99]
Need to rethink philosophy of Stack component and create new

**Comment by nin-jin** [comment]
stacker сейчас - лайаут, который располагает экраны горизонтально или друг над другом. В идеале он должен позволять размещать таким образом и больше 2 экранов. В случае расположения друг над другом, желательно:
1. Не рендерить те экраны, которые не видно.
2. Показывать тот экран, который в фокусе. Приложение по своей логике меняет фокус и от этого переключаются экраны.

**Comment by nin-jin** [comment]
Реализован  [$mol_book](https://github.com/eigenmethod/mol/tree/master/book).
